/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s3[7] = {0, 1, 2, 9, 10, 11, 12};
static const casadi_int casadi_s4[7] = {0, 3, 6, 9, 13, 17, 21};
static const casadi_int casadi_s5[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s6[7] = {3, 4, 5, 13, 14, 15, 16};
static const casadi_int casadi_s7[7] = {1, 4, 7, 10, 14, 18, 22};
static const casadi_int casadi_s8[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s9[7] = {6, 7, 8, 17, 18, 19, 20};
static const casadi_int casadi_s10[7] = {2, 5, 8, 11, 15, 19, 23};
static const casadi_int casadi_s11[39] = {11, 11, 0, 3, 6, 9, 13, 17, 21, 25, 25, 25, 25, 25, 0, 1, 2, 0, 1, 2, 0, 1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6};
static const casadi_int casadi_s12[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s13[3] = {0, 0, 0};
static const casadi_int casadi_s14[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s15[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s16[14] = {0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_e_fun_jac_hess:(i0[11],i1[],i2[],i3[17])->(o0,o1[11],o2[11x11,25nz],o3[],o4[0x11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+53, *w23=w+56, *w24=w+65, *w25=w+69, *w26=w+73, *w27=w+76, *w28=w+79, w29, *w30=w+89, *w31=w+114, w32, w33, w34, *w35=w+123, *w36=w+130, *w44=w+132;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #21: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #24: @9 = input[0][3] */
  w9 = arg[0] ? arg[0][3] : 0;
  /* #25: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #26: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #27: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #28: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #29: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #30: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #31: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #32: @21 = vertcat(@2, @3, @4, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #33: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #34: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #35: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #36: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #37: @2 = 2.1 */
  w2 = 2.1000000000000001e+00;
  /* #38: (@23[0] = @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #39: @2 = 2.1 */
  w2 = 2.1000000000000001e+00;
  /* #40: (@23[4] = @2) */
  for (rr=w23+4, ss=(&w2); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #41: @2 = 2.1 */
  w2 = 2.1000000000000001e+00;
  /* #42: (@23[8] = @2) */
  for (rr=w23+8, ss=(&w2); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #43: @1 = mac(@22,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #44: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #45: @2 = 1 */
  w2 = 1.;
  /* #46: @6 = (-@6) */
  w6 = (- w6 );
  /* #47: @7 = (-@7) */
  w7 = (- w7 );
  /* #48: @8 = (-@8) */
  w8 = (- w8 );
  /* #49: @24 = vertcat(@5, @6, @7, @8) */
  rr=w24;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #50: @25 = @19[3:7] */
  for (rr=w25, ss=w19+3; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #51: @5 = ||@25||_F */
  w5 = sqrt(casadi_dot(4, w25, w25));
  /* #52: @24 = (@24/@5) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w5;
  /* #53: @5 = @24[0] */
  for (rr=(&w5), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #54: @6 = (@5*@9) */
  w6  = (w5*w9);
  /* #55: @7 = @24[1] */
  for (rr=(&w7), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #56: @8 = (@7*@10) */
  w8  = (w7*w10);
  /* #57: @6 = (@6-@8) */
  w6 -= w8;
  /* #58: @8 = @24[2] */
  for (rr=(&w8), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #59: @3 = (@8*@11) */
  w3  = (w8*w11);
  /* #60: @6 = (@6-@3) */
  w6 -= w3;
  /* #61: @3 = @24[3] */
  for (rr=(&w3), ss=w24+3; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #62: @4 = (@3*@12) */
  w4  = (w3*w12);
  /* #63: @6 = (@6-@4) */
  w6 -= w4;
  /* #64: @2 = (@2-@6) */
  w2 -= w6;
  /* #65: @0 = (@0+@2) */
  w0 += w2;
  /* #66: @2 = 0 */
  w2 = 0.;
  /* #67: @4 = 7 */
  w4 = 7.;
  /* #68: @13 = (@5*@10) */
  w13  = (w5*w10);
  /* #69: @14 = (@7*@9) */
  w14  = (w7*w9);
  /* #70: @13 = (@13+@14) */
  w13 += w14;
  /* #71: @14 = (@8*@12) */
  w14  = (w8*w12);
  /* #72: @13 = (@13+@14) */
  w13 += w14;
  /* #73: @14 = (@3*@11) */
  w14  = (w3*w11);
  /* #74: @13 = (@13-@14) */
  w13 -= w14;
  /* #75: @14 = (@5*@11) */
  w14  = (w5*w11);
  /* #76: @15 = (@7*@12) */
  w15  = (w7*w12);
  /* #77: @14 = (@14-@15) */
  w14 -= w15;
  /* #78: @15 = (@8*@9) */
  w15  = (w8*w9);
  /* #79: @14 = (@14+@15) */
  w14 += w15;
  /* #80: @15 = (@3*@10) */
  w15  = (w3*w10);
  /* #81: @14 = (@14+@15) */
  w14 += w15;
  /* #82: @12 = (@5*@12) */
  w12  = (w5*w12);
  /* #83: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #84: @12 = (@12+@11) */
  w12 += w11;
  /* #85: @10 = (@8*@10) */
  w10  = (w8*w10);
  /* #86: @12 = (@12-@10) */
  w12 -= w10;
  /* #87: @9 = (@3*@9) */
  w9  = (w3*w9);
  /* #88: @12 = (@12+@9) */
  w12 += w9;
  /* #89: @24 = vertcat(@6, @13, @14, @12) */
  rr=w24;
  *rr++ = w6;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w12;
  /* #90: @22 = @24[1:4] */
  for (rr=w22, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #91: @22 = @22' */
  /* #92: @22 = (@4*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #93: @26 = @24[1:4] */
  for (rr=w26, ss=w24+1; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #94: @2 = mac(@22,@26,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #95: @0 = (@0+@2) */
  w0 += w2;
  /* #96: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #97: @21 = zeros(11x1) */
  casadi_clear(w21, 11);
  /* #98: @1 = @1' */
  /* #99: @27 = zeros(1x3) */
  casadi_clear(w27, 3);
  /* #100: @20 = @20' */
  /* #101: @28 = @23' */
  for (i=0, rr=w28, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #102: @27 = mac(@20,@28,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #103: @27 = @27' */
  /* #104: @1 = (@1+@27) */
  for (i=0, rr=w1, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #105: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #106: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #107: {@0, @2, @6, @13, @14, @12, @9, @10, @11, @15, @16} = vertsplit(@21) */
  w0 = w21[0];
  w2 = w21[1];
  w6 = w21[2];
  w13 = w21[3];
  w14 = w21[4];
  w12 = w21[5];
  w9 = w21[6];
  w10 = w21[7];
  w11 = w21[8];
  w15 = w21[9];
  w16 = w21[10];
  /* #108: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #109: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #110: output[1][2] = @6 */
  if (res[1]) res[1][2] = w6;
  /* #111: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #112: @22 = @22' */
  /* #113: (@24[1:4] += @22) */
  for (rr=w24+1, ss=w22; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #114: @26 = @26' */
  /* #115: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #116: @26 = @26' */
  /* #117: (@24[1:4] += @26) */
  for (rr=w24+1, ss=w26; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #118: {@6, @2, @0, @17} = vertsplit(@24) */
  w6 = w24[0];
  w2 = w24[1];
  w0 = w24[2];
  w17 = w24[3];
  /* #119: @18 = (@3*@17) */
  w18  = (w3*w17);
  /* #120: @29 = (@8*@0) */
  w29  = (w8*w0);
  /* #121: @18 = (@18+@29) */
  w18 += w29;
  /* #122: @29 = (@7*@2) */
  w29  = (w7*w2);
  /* #123: @18 = (@18+@29) */
  w18 += w29;
  /* #124: @29 = -1 */
  w29 = -1.;
  /* #125: @29 = (@29+@6) */
  w29 += w6;
  /* #126: @6 = (@5*@29) */
  w6  = (w5*w29);
  /* #127: @18 = (@18+@6) */
  w18 += w6;
  /* #128: @18 = (@18+@13) */
  w18 += w13;
  /* #129: output[1][3] = @18 */
  if (res[1]) res[1][3] = w18;
  /* #130: @18 = (@3*@0) */
  w18  = (w3*w0);
  /* #131: @13 = (@8*@17) */
  w13  = (w8*w17);
  /* #132: @18 = (@18-@13) */
  w18 -= w13;
  /* #133: @13 = (@5*@2) */
  w13  = (w5*w2);
  /* #134: @18 = (@18+@13) */
  w18 += w13;
  /* #135: @13 = (@7*@29) */
  w13  = (w7*w29);
  /* #136: @18 = (@18-@13) */
  w18 -= w13;
  /* #137: @18 = (@18+@14) */
  w18 += w14;
  /* #138: output[1][4] = @18 */
  if (res[1]) res[1][4] = w18;
  /* #139: @18 = (@7*@17) */
  w18  = (w7*w17);
  /* #140: @14 = (@5*@0) */
  w14  = (w5*w0);
  /* #141: @18 = (@18+@14) */
  w18 += w14;
  /* #142: @14 = (@3*@2) */
  w14  = (w3*w2);
  /* #143: @18 = (@18-@14) */
  w18 -= w14;
  /* #144: @14 = (@8*@29) */
  w14  = (w8*w29);
  /* #145: @18 = (@18-@14) */
  w18 -= w14;
  /* #146: @18 = (@18+@12) */
  w18 += w12;
  /* #147: output[1][5] = @18 */
  if (res[1]) res[1][5] = w18;
  /* #148: @17 = (@5*@17) */
  w17  = (w5*w17);
  /* #149: @0 = (@7*@0) */
  w0  = (w7*w0);
  /* #150: @17 = (@17-@0) */
  w17 -= w0;
  /* #151: @2 = (@8*@2) */
  w2  = (w8*w2);
  /* #152: @17 = (@17+@2) */
  w17 += w2;
  /* #153: @29 = (@3*@29) */
  w29  = (w3*w29);
  /* #154: @17 = (@17-@29) */
  w17 -= w29;
  /* #155: @17 = (@17+@9) */
  w17 += w9;
  /* #156: output[1][6] = @17 */
  if (res[1]) res[1][6] = w17;
  /* #157: output[1][7] = @10 */
  if (res[1]) res[1][7] = w10;
  /* #158: output[1][8] = @11 */
  if (res[1]) res[1][8] = w11;
  /* #159: output[1][9] = @15 */
  if (res[1]) res[1][9] = w15;
  /* #160: output[1][10] = @16 */
  if (res[1]) res[1][10] = w16;
  /* #161: @30 = zeros(11x11,25nz) */
  casadi_clear(w30, 25);
  /* #162: @21 = zeros(11x1) */
  casadi_clear(w21, 11);
  /* #163: @26 = zeros(1x3) */
  casadi_clear(w26, 3);
  /* #164: @31 = ones(11x1,6nz) */
  casadi_fill(w31, 6, 1.);
  /* #165: {@16, NULL, NULL, @15, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@31) */
  w16 = w31[0];
  w15 = w31[1];
  /* #166: @11 = @16[0] */
  for (rr=(&w11), ss=(&w16)+0; ss!=(&w16)+1; ss+=1) *rr++ = *ss;
  /* #167: @11 = (-@11) */
  w11 = (- w11 );
  /* #168: @16 = @11' */
  casadi_copy((&w11), 1, (&w16));
  /* #169: @26 = mac(@16,@23,@26) */
  casadi_mtimes((&w16), casadi_s2, w23, casadi_s1, w26, casadi_s0, w, 0);
  /* #170: @26 = @26' */
  /* #171: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #172: @11 = @11' */
  /* #173: @22 = mac(@11,@28,@22) */
  casadi_mtimes((&w11), casadi_s2, w28, casadi_s1, w22, casadi_s0, w, 0);
  /* #174: @22 = @22' */
  /* #175: @26 = (@26+@22) */
  for (i=0, rr=w26, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #176: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (- *cs++ );
  /* #177: (@21[:3] += @26) */
  for (rr=w21+0, ss=w26; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #178: {@11, @16, @10, @17, @9, @29, @2, @0, @18, @12, @14} = vertsplit(@21) */
  w11 = w21[0];
  w16 = w21[1];
  w10 = w21[2];
  w17 = w21[3];
  w9 = w21[4];
  w29 = w21[5];
  w2 = w21[6];
  w0 = w21[7];
  w18 = w21[8];
  w12 = w21[9];
  w14 = w21[10];
  /* #179: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #180: @13 = (@5*@15) */
  w13  = (w5*w15);
  /* #181: @6 = (@7*@15) */
  w6  = (w7*w15);
  /* #182: @32 = (@8*@15) */
  w32  = (w8*w15);
  /* #183: @15 = (@3*@15) */
  w15  = (w3*w15);
  /* #184: @25 = vertcat(@13, @6, @32, @15) */
  rr=w25;
  *rr++ = w13;
  *rr++ = w6;
  *rr++ = w32;
  *rr++ = w15;
  /* #185: @26 = @25[1:4] */
  for (rr=w26, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #186: @26 = @26' */
  /* #187: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #188: @26 = @26' */
  /* #189: (@24[1:4] += @26) */
  for (rr=w24+1, ss=w26; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #190: @26 = @25[1:4] */
  for (rr=w26, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #191: @26 = @26' */
  /* #192: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #193: @26 = @26' */
  /* #194: (@24[1:4] += @26) */
  for (rr=w24+1, ss=w26; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #195: {@13, @6, @32, @15} = vertsplit(@24) */
  w13 = w24[0];
  w6 = w24[1];
  w32 = w24[2];
  w15 = w24[3];
  /* #196: @33 = (@3*@15) */
  w33  = (w3*w15);
  /* #197: @34 = (@8*@32) */
  w34  = (w8*w32);
  /* #198: @33 = (@33+@34) */
  w33 += w34;
  /* #199: @34 = (@7*@6) */
  w34  = (w7*w6);
  /* #200: @33 = (@33+@34) */
  w33 += w34;
  /* #201: @34 = (@5*@13) */
  w34  = (w5*w13);
  /* #202: @33 = (@33+@34) */
  w33 += w34;
  /* #203: @33 = (@33+@17) */
  w33 += w17;
  /* #204: @17 = (@3*@32) */
  w17  = (w3*w32);
  /* #205: @34 = (@8*@15) */
  w34  = (w8*w15);
  /* #206: @17 = (@17-@34) */
  w17 -= w34;
  /* #207: @34 = (@5*@6) */
  w34  = (w5*w6);
  /* #208: @17 = (@17+@34) */
  w17 += w34;
  /* #209: @34 = (@7*@13) */
  w34  = (w7*w13);
  /* #210: @17 = (@17-@34) */
  w17 -= w34;
  /* #211: @17 = (@17+@9) */
  w17 += w9;
  /* #212: @9 = (@7*@15) */
  w9  = (w7*w15);
  /* #213: @34 = (@5*@32) */
  w34  = (w5*w32);
  /* #214: @9 = (@9+@34) */
  w9 += w34;
  /* #215: @34 = (@3*@6) */
  w34  = (w3*w6);
  /* #216: @9 = (@9-@34) */
  w9 -= w34;
  /* #217: @34 = (@8*@13) */
  w34  = (w8*w13);
  /* #218: @9 = (@9-@34) */
  w9 -= w34;
  /* #219: @9 = (@9+@29) */
  w9 += w29;
  /* #220: @15 = (@5*@15) */
  w15  = (w5*w15);
  /* #221: @32 = (@7*@32) */
  w32  = (w7*w32);
  /* #222: @15 = (@15-@32) */
  w15 -= w32;
  /* #223: @6 = (@8*@6) */
  w6  = (w8*w6);
  /* #224: @15 = (@15+@6) */
  w15 += w6;
  /* #225: @13 = (@3*@13) */
  w13  = (w3*w13);
  /* #226: @15 = (@15-@13) */
  w15 -= w13;
  /* #227: @15 = (@15+@2) */
  w15 += w2;
  /* #228: @21 = vertcat(@11, @16, @10, @33, @17, @9, @15, @0, @18, @12, @14) */
  rr=w21;
  *rr++ = w11;
  *rr++ = w16;
  *rr++ = w10;
  *rr++ = w33;
  *rr++ = w17;
  *rr++ = w9;
  *rr++ = w15;
  *rr++ = w0;
  *rr++ = w18;
  *rr++ = w12;
  *rr++ = w14;
  /* #229: @35 = @21[:7] */
  for (rr=w35, ss=w21+0; ss!=w21+7; ss+=1) *rr++ = *ss;
  /* #230: (@30[0, 1, 2, 9, 10, 11, 12] = @35) */
  for (cii=casadi_s3, rr=w30, ss=w35; cii!=casadi_s3+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #231: @35 = @21[:7] */
  for (rr=w35, ss=w21+0; ss!=w21+7; ss+=1) *rr++ = *ss;
  /* #232: (@30[0, 3, 6, 9, 13, 17, 21] = @35) */
  for (cii=casadi_s4, rr=w30, ss=w35; cii!=casadi_s4+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #233: @21 = zeros(11x1) */
  casadi_clear(w21, 11);
  /* #234: @26 = zeros(1x3) */
  casadi_clear(w26, 3);
  /* #235: @36 = ones(11x1,2nz) */
  casadi_fill(w36, 2, 1.);
  /* #236: {NULL, @11, NULL, NULL, @16, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@36) */
  w11 = w36[0];
  w16 = w36[1];
  /* #237: @10 = @11[0] */
  for (rr=(&w10), ss=(&w11)+0; ss!=(&w11)+1; ss+=1) *rr++ = *ss;
  /* #238: @10 = (-@10) */
  w10 = (- w10 );
  /* #239: @11 = @10' */
  casadi_copy((&w10), 1, (&w11));
  /* #240: @26 = mac(@11,@23,@26) */
  casadi_mtimes((&w11), casadi_s5, w23, casadi_s1, w26, casadi_s0, w, 0);
  /* #241: @26 = @26' */
  /* #242: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #243: @10 = @10' */
  /* #244: @22 = mac(@10,@28,@22) */
  casadi_mtimes((&w10), casadi_s5, w28, casadi_s1, w22, casadi_s0, w, 0);
  /* #245: @22 = @22' */
  /* #246: @26 = (@26+@22) */
  for (i=0, rr=w26, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #247: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (- *cs++ );
  /* #248: (@21[:3] += @26) */
  for (rr=w21+0, ss=w26; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #249: {@10, @11, @33, @17, @9, @15, @0, @18, @12, @14, @2} = vertsplit(@21) */
  w10 = w21[0];
  w11 = w21[1];
  w33 = w21[2];
  w17 = w21[3];
  w9 = w21[4];
  w15 = w21[5];
  w0 = w21[6];
  w18 = w21[7];
  w12 = w21[8];
  w14 = w21[9];
  w2 = w21[10];
  /* #250: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #251: @13 = (@7*@16) */
  w13  = (w7*w16);
  /* #252: @13 = (-@13) */
  w13 = (- w13 );
  /* #253: @6 = (@5*@16) */
  w6  = (w5*w16);
  /* #254: @32 = (@3*@16) */
  w32  = (w3*w16);
  /* #255: @16 = (@8*@16) */
  w16  = (w8*w16);
  /* #256: @16 = (-@16) */
  w16 = (- w16 );
  /* #257: @25 = vertcat(@13, @6, @32, @16) */
  rr=w25;
  *rr++ = w13;
  *rr++ = w6;
  *rr++ = w32;
  *rr++ = w16;
  /* #258: @26 = @25[1:4] */
  for (rr=w26, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #259: @26 = @26' */
  /* #260: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #261: @26 = @26' */
  /* #262: (@24[1:4] += @26) */
  for (rr=w24+1, ss=w26; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #263: @26 = @25[1:4] */
  for (rr=w26, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #264: @26 = @26' */
  /* #265: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #266: @26 = @26' */
  /* #267: (@24[1:4] += @26) */
  for (rr=w24+1, ss=w26; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #268: {@13, @6, @32, @16} = vertsplit(@24) */
  w13 = w24[0];
  w6 = w24[1];
  w32 = w24[2];
  w16 = w24[3];
  /* #269: @29 = (@3*@16) */
  w29  = (w3*w16);
  /* #270: @34 = (@8*@32) */
  w34  = (w8*w32);
  /* #271: @29 = (@29+@34) */
  w29 += w34;
  /* #272: @34 = (@7*@6) */
  w34  = (w7*w6);
  /* #273: @29 = (@29+@34) */
  w29 += w34;
  /* #274: @34 = (@5*@13) */
  w34  = (w5*w13);
  /* #275: @29 = (@29+@34) */
  w29 += w34;
  /* #276: @29 = (@29+@17) */
  w29 += w17;
  /* #277: @17 = (@3*@32) */
  w17  = (w3*w32);
  /* #278: @34 = (@8*@16) */
  w34  = (w8*w16);
  /* #279: @17 = (@17-@34) */
  w17 -= w34;
  /* #280: @34 = (@5*@6) */
  w34  = (w5*w6);
  /* #281: @17 = (@17+@34) */
  w17 += w34;
  /* #282: @34 = (@7*@13) */
  w34  = (w7*w13);
  /* #283: @17 = (@17-@34) */
  w17 -= w34;
  /* #284: @17 = (@17+@9) */
  w17 += w9;
  /* #285: @9 = (@7*@16) */
  w9  = (w7*w16);
  /* #286: @34 = (@5*@32) */
  w34  = (w5*w32);
  /* #287: @9 = (@9+@34) */
  w9 += w34;
  /* #288: @34 = (@3*@6) */
  w34  = (w3*w6);
  /* #289: @9 = (@9-@34) */
  w9 -= w34;
  /* #290: @34 = (@8*@13) */
  w34  = (w8*w13);
  /* #291: @9 = (@9-@34) */
  w9 -= w34;
  /* #292: @9 = (@9+@15) */
  w9 += w15;
  /* #293: @16 = (@5*@16) */
  w16  = (w5*w16);
  /* #294: @32 = (@7*@32) */
  w32  = (w7*w32);
  /* #295: @16 = (@16-@32) */
  w16 -= w32;
  /* #296: @6 = (@8*@6) */
  w6  = (w8*w6);
  /* #297: @16 = (@16+@6) */
  w16 += w6;
  /* #298: @13 = (@3*@13) */
  w13  = (w3*w13);
  /* #299: @16 = (@16-@13) */
  w16 -= w13;
  /* #300: @16 = (@16+@0) */
  w16 += w0;
  /* #301: @21 = vertcat(@10, @11, @33, @29, @17, @9, @16, @18, @12, @14, @2) */
  rr=w21;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w33;
  *rr++ = w29;
  *rr++ = w17;
  *rr++ = w9;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w2;
  /* #302: @35 = @21[:7] */
  for (rr=w35, ss=w21+0; ss!=w21+7; ss+=1) *rr++ = *ss;
  /* #303: (@30[3, 4, 5, 13, 14, 15, 16] = @35) */
  for (cii=casadi_s6, rr=w30, ss=w35; cii!=casadi_s6+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #304: @35 = @21[:7] */
  for (rr=w35, ss=w21+0; ss!=w21+7; ss+=1) *rr++ = *ss;
  /* #305: (@30[1, 4, 7, 10, 14, 18, 22] = @35) */
  for (cii=casadi_s7, rr=w30, ss=w35; cii!=casadi_s7+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #306: @21 = zeros(11x1) */
  casadi_clear(w21, 11);
  /* #307: @26 = zeros(1x3) */
  casadi_clear(w26, 3);
  /* #308: @36 = ones(11x1,2nz) */
  casadi_fill(w36, 2, 1.);
  /* #309: {NULL, NULL, @10, NULL, NULL, @11, NULL, NULL, NULL, NULL, NULL} = vertsplit(@36) */
  w10 = w36[0];
  w11 = w36[1];
  /* #310: @33 = @10[0] */
  for (rr=(&w33), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #311: @33 = (-@33) */
  w33 = (- w33 );
  /* #312: @10 = @33' */
  casadi_copy((&w33), 1, (&w10));
  /* #313: @26 = mac(@10,@23,@26) */
  casadi_mtimes((&w10), casadi_s8, w23, casadi_s1, w26, casadi_s0, w, 0);
  /* #314: @26 = @26' */
  /* #315: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #316: @33 = @33' */
  /* #317: @22 = mac(@33,@28,@22) */
  casadi_mtimes((&w33), casadi_s8, w28, casadi_s1, w22, casadi_s0, w, 0);
  /* #318: @22 = @22' */
  /* #319: @26 = (@26+@22) */
  for (i=0, rr=w26, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #320: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) *rr++ = (- *cs++ );
  /* #321: (@21[:3] += @26) */
  for (rr=w21+0, ss=w26; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #322: {@33, @10, @29, @17, @9, @16, @18, @12, @14, @2, @0} = vertsplit(@21) */
  w33 = w21[0];
  w10 = w21[1];
  w29 = w21[2];
  w17 = w21[3];
  w9 = w21[4];
  w16 = w21[5];
  w18 = w21[6];
  w12 = w21[7];
  w14 = w21[8];
  w2 = w21[9];
  w0 = w21[10];
  /* #323: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #324: @13 = (@8*@11) */
  w13  = (w8*w11);
  /* #325: @13 = (-@13) */
  w13 = (- w13 );
  /* #326: @6 = (@3*@11) */
  w6  = (w3*w11);
  /* #327: @6 = (-@6) */
  w6 = (- w6 );
  /* #328: @32 = (@5*@11) */
  w32  = (w5*w11);
  /* #329: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #330: @25 = vertcat(@13, @6, @32, @11) */
  rr=w25;
  *rr++ = w13;
  *rr++ = w6;
  *rr++ = w32;
  *rr++ = w11;
  /* #331: @26 = @25[1:4] */
  for (rr=w26, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #332: @26 = @26' */
  /* #333: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #334: @26 = @26' */
  /* #335: (@24[1:4] += @26) */
  for (rr=w24+1, ss=w26; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #336: @26 = @25[1:4] */
  for (rr=w26, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #337: @26 = @26' */
  /* #338: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #339: @26 = @26' */
  /* #340: (@24[1:4] += @26) */
  for (rr=w24+1, ss=w26; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #341: {@13, @6, @32, @11} = vertsplit(@24) */
  w13 = w24[0];
  w6 = w24[1];
  w32 = w24[2];
  w11 = w24[3];
  /* #342: @15 = (@3*@11) */
  w15  = (w3*w11);
  /* #343: @34 = (@8*@32) */
  w34  = (w8*w32);
  /* #344: @15 = (@15+@34) */
  w15 += w34;
  /* #345: @34 = (@7*@6) */
  w34  = (w7*w6);
  /* #346: @15 = (@15+@34) */
  w15 += w34;
  /* #347: @34 = (@5*@13) */
  w34  = (w5*w13);
  /* #348: @15 = (@15+@34) */
  w15 += w34;
  /* #349: @15 = (@15+@17) */
  w15 += w17;
  /* #350: @17 = (@3*@32) */
  w17  = (w3*w32);
  /* #351: @34 = (@8*@11) */
  w34  = (w8*w11);
  /* #352: @17 = (@17-@34) */
  w17 -= w34;
  /* #353: @34 = (@5*@6) */
  w34  = (w5*w6);
  /* #354: @17 = (@17+@34) */
  w17 += w34;
  /* #355: @34 = (@7*@13) */
  w34  = (w7*w13);
  /* #356: @17 = (@17-@34) */
  w17 -= w34;
  /* #357: @17 = (@17+@9) */
  w17 += w9;
  /* #358: @9 = (@7*@11) */
  w9  = (w7*w11);
  /* #359: @34 = (@5*@32) */
  w34  = (w5*w32);
  /* #360: @9 = (@9+@34) */
  w9 += w34;
  /* #361: @34 = (@3*@6) */
  w34  = (w3*w6);
  /* #362: @9 = (@9-@34) */
  w9 -= w34;
  /* #363: @34 = (@8*@13) */
  w34  = (w8*w13);
  /* #364: @9 = (@9-@34) */
  w9 -= w34;
  /* #365: @9 = (@9+@16) */
  w9 += w16;
  /* #366: @11 = (@5*@11) */
  w11  = (w5*w11);
  /* #367: @32 = (@7*@32) */
  w32  = (w7*w32);
  /* #368: @11 = (@11-@32) */
  w11 -= w32;
  /* #369: @6 = (@8*@6) */
  w6  = (w8*w6);
  /* #370: @11 = (@11+@6) */
  w11 += w6;
  /* #371: @13 = (@3*@13) */
  w13  = (w3*w13);
  /* #372: @11 = (@11-@13) */
  w11 -= w13;
  /* #373: @11 = (@11+@18) */
  w11 += w18;
  /* #374: @21 = vertcat(@33, @10, @29, @15, @17, @9, @11, @12, @14, @2, @0) */
  rr=w21;
  *rr++ = w33;
  *rr++ = w10;
  *rr++ = w29;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w2;
  *rr++ = w0;
  /* #375: @35 = @21[:7] */
  for (rr=w35, ss=w21+0; ss!=w21+7; ss+=1) *rr++ = *ss;
  /* #376: (@30[6, 7, 8, 17, 18, 19, 20] = @35) */
  for (cii=casadi_s9, rr=w30, ss=w35; cii!=casadi_s9+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #377: @35 = @21[:7] */
  for (rr=w35, ss=w21+0; ss!=w21+7; ss+=1) *rr++ = *ss;
  /* #378: (@30[2, 5, 8, 11, 15, 19, 23] = @35) */
  for (cii=casadi_s10, rr=w30, ss=w35; cii!=casadi_s10+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #379: @37 = 00 */
  /* #380: @38 = 00 */
  /* #381: @39 = 00 */
  /* #382: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #383: @33 = ones(11x1,1nz) */
  w33 = 1.;
  /* #384: {NULL, NULL, NULL, NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@33) */
  w10 = w33;
  /* #385: @33 = (@3*@10) */
  w33  = (w3*w10);
  /* #386: @33 = (-@33) */
  w33 = (- w33 );
  /* #387: @29 = (@8*@10) */
  w29  = (w8*w10);
  /* #388: @15 = (@7*@10) */
  w15  = (w7*w10);
  /* #389: @15 = (-@15) */
  w15 = (- w15 );
  /* #390: @10 = (@5*@10) */
  w10  = (w5*w10);
  /* #391: @25 = vertcat(@33, @29, @15, @10) */
  rr=w25;
  *rr++ = w33;
  *rr++ = w29;
  *rr++ = w15;
  *rr++ = w10;
  /* #392: @26 = @25[1:4] */
  for (rr=w26, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #393: @26 = @26' */
  /* #394: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #395: @26 = @26' */
  /* #396: (@24[1:4] += @26) */
  for (rr=w24+1, ss=w26; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #397: @26 = @25[1:4] */
  for (rr=w26, ss=w25+1; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #398: @26 = @26' */
  /* #399: @26 = (@4*@26) */
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #400: @26 = @26' */
  /* #401: (@24[1:4] += @26) */
  for (rr=w24+1, ss=w26; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #402: {@4, @33, @29, @15} = vertsplit(@24) */
  w4 = w24[0];
  w33 = w24[1];
  w29 = w24[2];
  w15 = w24[3];
  /* #403: @10 = (@3*@15) */
  w10  = (w3*w15);
  /* #404: @17 = (@8*@29) */
  w17  = (w8*w29);
  /* #405: @10 = (@10+@17) */
  w10 += w17;
  /* #406: @17 = (@7*@33) */
  w17  = (w7*w33);
  /* #407: @10 = (@10+@17) */
  w10 += w17;
  /* #408: @17 = (@5*@4) */
  w17  = (w5*w4);
  /* #409: @10 = (@10+@17) */
  w10 += w17;
  /* #410: @17 = (@3*@29) */
  w17  = (w3*w29);
  /* #411: @9 = (@8*@15) */
  w9  = (w8*w15);
  /* #412: @17 = (@17-@9) */
  w17 -= w9;
  /* #413: @9 = (@5*@33) */
  w9  = (w5*w33);
  /* #414: @17 = (@17+@9) */
  w17 += w9;
  /* #415: @9 = (@7*@4) */
  w9  = (w7*w4);
  /* #416: @17 = (@17-@9) */
  w17 -= w9;
  /* #417: @9 = (@7*@15) */
  w9  = (w7*w15);
  /* #418: @11 = (@5*@29) */
  w11  = (w5*w29);
  /* #419: @9 = (@9+@11) */
  w9 += w11;
  /* #420: @11 = (@3*@33) */
  w11  = (w3*w33);
  /* #421: @9 = (@9-@11) */
  w9 -= w11;
  /* #422: @11 = (@8*@4) */
  w11  = (w8*w4);
  /* #423: @9 = (@9-@11) */
  w9 -= w11;
  /* #424: @5 = (@5*@15) */
  w5 *= w15;
  /* #425: @7 = (@7*@29) */
  w7 *= w29;
  /* #426: @5 = (@5-@7) */
  w5 -= w7;
  /* #427: @8 = (@8*@33) */
  w8 *= w33;
  /* #428: @5 = (@5+@8) */
  w5 += w8;
  /* #429: @3 = (@3*@4) */
  w3 *= w4;
  /* #430: @5 = (@5-@3) */
  w5 -= w3;
  /* #431: @40 = 00 */
  /* #432: @41 = 00 */
  /* #433: @42 = 00 */
  /* #434: @43 = 00 */
  /* #435: @24 = vertcat(@37, @38, @39, @10, @17, @9, @5, @40, @41, @42, @43) */
  rr=w24;
  *rr++ = w10;
  *rr++ = w17;
  *rr++ = w9;
  *rr++ = w5;
  /* #436: @25 = @24[:4] */
  for (rr=w25, ss=w24+0; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #437: (@30[21:25] = @25) */
  for (rr=w30+21, ss=w25; rr!=w30+25; rr+=1) *rr = *ss++;
  /* #438: @25 = @24[:4] */
  for (rr=w25, ss=w24+0; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #439: (@30[12:28:4] = @25) */
  for (rr=w30+12, ss=w25; rr!=w30+28; rr+=4) *rr = *ss++;
  /* #440: @44 = @30' */
  casadi_trans(w30,casadi_s11, w44, casadi_s11, iw);
  /* #441: output[2][0] = @44 */
  casadi_copy(w44, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    case 1: return casadi_s13;
    case 2: return casadi_s13;
    case 3: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s15;
    case 1: return casadi_s12;
    case 2: return casadi_s11;
    case 3: return casadi_s13;
    case 4: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 12;
  if (sz_w) *sz_w = 157;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
