/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s6[11] = {0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28};
static const casadi_int casadi_s7[11] = {0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37};
static const casadi_int casadi_s8[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s9[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s10[11] = {4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32};
static const casadi_int casadi_s11[11] = {1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38};
static const casadi_int casadi_s12[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s14[11] = {8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36};
static const casadi_int casadi_s15[11] = {2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39};
static const casadi_int casadi_s16[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s17[59] = {15, 15, 0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37, 41, 41, 41, 41, 41, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 7, 8, 9, 10, 7, 8, 9, 10, 7, 8, 9, 10, 7, 8, 9, 10};
static const casadi_int casadi_s18[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s19[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s20[3] = {0, 0, 0};
static const casadi_int casadi_s21[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s22[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s23[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s24[18] = {0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_fun_jac_hess:(i0[11],i1[4],i2[],i3[17])->(o0,o1[15],o2[15x15,41nz],o3[],o4[0x15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+53, *w23=w+56, *w24=w+65, *w25=w+69, *w26=w+73, *w27=w+77, *w28=w+93, *w29=w+97, *w30=w+100, *w31=w+116, *w32=w+119, w33, *w34=w+129, *w35=w+170, w39, w40, w41, w42, w43, w44, w45, *w46=w+184, *w47=w+199, *w52=w+201, *w53=w+209, *w54=w+217;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #21: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #24: @9 = input[0][3] */
  w9 = arg[0] ? arg[0][3] : 0;
  /* #25: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #26: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #27: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #28: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #29: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #30: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #31: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #32: @21 = vertcat(@2, @3, @4, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #33: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #34: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #35: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #36: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #37: @2 = 2.1 */
  w2 = 2.1000000000000001e+00;
  /* #38: (@23[0] = @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #39: @2 = 2.1 */
  w2 = 2.1000000000000001e+00;
  /* #40: (@23[4] = @2) */
  for (rr=w23+4, ss=(&w2); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #41: @2 = 2.1 */
  w2 = 2.1000000000000001e+00;
  /* #42: (@23[8] = @2) */
  for (rr=w23+8, ss=(&w2); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #43: @1 = mac(@22,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #44: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #45: @2 = 0 */
  w2 = 0.;
  /* #46: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #47: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #48: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #49: @13 = input[1][2] */
  w13 = arg[1] ? arg[1][2] : 0;
  /* #50: @14 = input[1][3] */
  w14 = arg[1] ? arg[1][3] : 0;
  /* #51: @25 = vertcat(@3, @4, @13, @14) */
  rr=w25;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w13;
  *rr++ = w14;
  /* #52: @26 = @25' */
  casadi_copy(w25, 4, w26);
  /* #53: @27 = zeros(4x4) */
  casadi_clear(w27, 16);
  /* #54: @3 = 1 */
  w3 = 1.;
  /* #55: (@27[0] = @3) */
  for (rr=w27+0, ss=(&w3); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #56: @3 = 1 */
  w3 = 1.;
  /* #57: (@27[5] = @3) */
  for (rr=w27+5, ss=(&w3); rr!=w27+6; rr+=1) *rr = *ss++;
  /* #58: @3 = 1 */
  w3 = 1.;
  /* #59: (@27[10] = @3) */
  for (rr=w27+10, ss=(&w3); rr!=w27+11; rr+=1) *rr = *ss++;
  /* #60: @3 = 1 */
  w3 = 1.;
  /* #61: (@27[15] = @3) */
  for (rr=w27+15, ss=(&w3); rr!=w27+16; rr+=1) *rr = *ss++;
  /* #62: @24 = mac(@26,@27,@24) */
  for (i=0, rr=w24; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #63: @2 = mac(@24,@25,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #64: @0 = (@0+@2) */
  w0 += w2;
  /* #65: @2 = 1 */
  w2 = 1.;
  /* #66: @6 = (-@6) */
  w6 = (- w6 );
  /* #67: @7 = (-@7) */
  w7 = (- w7 );
  /* #68: @8 = (-@8) */
  w8 = (- w8 );
  /* #69: @26 = vertcat(@5, @6, @7, @8) */
  rr=w26;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #70: @28 = @19[3:7] */
  for (rr=w28, ss=w19+3; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #71: @5 = ||@28||_F */
  w5 = sqrt(casadi_dot(4, w28, w28));
  /* #72: @26 = (@26/@5) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w5;
  /* #73: @5 = @26[0] */
  for (rr=(&w5), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #74: @6 = (@5*@9) */
  w6  = (w5*w9);
  /* #75: @7 = @26[1] */
  for (rr=(&w7), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #76: @8 = (@7*@10) */
  w8  = (w7*w10);
  /* #77: @6 = (@6-@8) */
  w6 -= w8;
  /* #78: @8 = @26[2] */
  for (rr=(&w8), ss=w26+2; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #79: @3 = (@8*@11) */
  w3  = (w8*w11);
  /* #80: @6 = (@6-@3) */
  w6 -= w3;
  /* #81: @3 = @26[3] */
  for (rr=(&w3), ss=w26+3; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #82: @4 = (@3*@12) */
  w4  = (w3*w12);
  /* #83: @6 = (@6-@4) */
  w6 -= w4;
  /* #84: @2 = (@2-@6) */
  w2 -= w6;
  /* #85: @0 = (@0+@2) */
  w0 += w2;
  /* #86: @2 = 0 */
  w2 = 0.;
  /* #87: @4 = 7 */
  w4 = 7.;
  /* #88: @13 = (@5*@10) */
  w13  = (w5*w10);
  /* #89: @14 = (@7*@9) */
  w14  = (w7*w9);
  /* #90: @13 = (@13+@14) */
  w13 += w14;
  /* #91: @14 = (@8*@12) */
  w14  = (w8*w12);
  /* #92: @13 = (@13+@14) */
  w13 += w14;
  /* #93: @14 = (@3*@11) */
  w14  = (w3*w11);
  /* #94: @13 = (@13-@14) */
  w13 -= w14;
  /* #95: @14 = (@5*@11) */
  w14  = (w5*w11);
  /* #96: @15 = (@7*@12) */
  w15  = (w7*w12);
  /* #97: @14 = (@14-@15) */
  w14 -= w15;
  /* #98: @15 = (@8*@9) */
  w15  = (w8*w9);
  /* #99: @14 = (@14+@15) */
  w14 += w15;
  /* #100: @15 = (@3*@10) */
  w15  = (w3*w10);
  /* #101: @14 = (@14+@15) */
  w14 += w15;
  /* #102: @12 = (@5*@12) */
  w12  = (w5*w12);
  /* #103: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #104: @12 = (@12+@11) */
  w12 += w11;
  /* #105: @10 = (@8*@10) */
  w10  = (w8*w10);
  /* #106: @12 = (@12-@10) */
  w12 -= w10;
  /* #107: @9 = (@3*@9) */
  w9  = (w3*w9);
  /* #108: @12 = (@12+@9) */
  w12 += w9;
  /* #109: @26 = vertcat(@6, @13, @14, @12) */
  rr=w26;
  *rr++ = w6;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w12;
  /* #110: @22 = @26[1:4] */
  for (rr=w22, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #111: @22 = @22' */
  /* #112: @22 = (@4*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #113: @29 = @26[1:4] */
  for (rr=w29, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #114: @2 = mac(@22,@29,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w29+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #115: @0 = (@0+@2) */
  w0 += w2;
  /* #116: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #117: @24 = @24' */
  /* #118: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #119: @25 = @25' */
  /* #120: @30 = @27' */
  for (i=0, rr=w30, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #121: @26 = mac(@25,@30,@26) */
  for (i=0, rr=w26; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #122: @26 = @26' */
  /* #123: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #124: {@0, @2, @6, @13} = vertsplit(@24) */
  w0 = w24[0];
  w2 = w24[1];
  w6 = w24[2];
  w13 = w24[3];
  /* #125: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #126: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #127: output[1][2] = @6 */
  if (res[1]) res[1][2] = w6;
  /* #128: output[1][3] = @13 */
  if (res[1]) res[1][3] = w13;
  /* #129: @21 = zeros(11x1) */
  casadi_clear(w21, 11);
  /* #130: @1 = @1' */
  /* #131: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #132: @20 = @20' */
  /* #133: @32 = @23' */
  for (i=0, rr=w32, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #134: @31 = mac(@20,@32,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #135: @31 = @31' */
  /* #136: @1 = (@1+@31) */
  for (i=0, rr=w1, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #137: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #138: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #139: {@13, @6, @2, @0, @14, @12, @9, @10, @11, @15, @16} = vertsplit(@21) */
  w13 = w21[0];
  w6 = w21[1];
  w2 = w21[2];
  w0 = w21[3];
  w14 = w21[4];
  w12 = w21[5];
  w9 = w21[6];
  w10 = w21[7];
  w11 = w21[8];
  w15 = w21[9];
  w16 = w21[10];
  /* #140: output[1][4] = @13 */
  if (res[1]) res[1][4] = w13;
  /* #141: output[1][5] = @6 */
  if (res[1]) res[1][5] = w6;
  /* #142: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #143: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #144: @22 = @22' */
  /* #145: (@24[1:4] += @22) */
  for (rr=w24+1, ss=w22; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #146: @29 = @29' */
  /* #147: @29 = (@4*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #148: @29 = @29' */
  /* #149: (@24[1:4] += @29) */
  for (rr=w24+1, ss=w29; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #150: {@2, @6, @13, @17} = vertsplit(@24) */
  w2 = w24[0];
  w6 = w24[1];
  w13 = w24[2];
  w17 = w24[3];
  /* #151: @18 = (@3*@17) */
  w18  = (w3*w17);
  /* #152: @33 = (@8*@13) */
  w33  = (w8*w13);
  /* #153: @18 = (@18+@33) */
  w18 += w33;
  /* #154: @33 = (@7*@6) */
  w33  = (w7*w6);
  /* #155: @18 = (@18+@33) */
  w18 += w33;
  /* #156: @33 = -1 */
  w33 = -1.;
  /* #157: @33 = (@33+@2) */
  w33 += w2;
  /* #158: @2 = (@5*@33) */
  w2  = (w5*w33);
  /* #159: @18 = (@18+@2) */
  w18 += w2;
  /* #160: @18 = (@18+@0) */
  w18 += w0;
  /* #161: output[1][7] = @18 */
  if (res[1]) res[1][7] = w18;
  /* #162: @18 = (@3*@13) */
  w18  = (w3*w13);
  /* #163: @0 = (@8*@17) */
  w0  = (w8*w17);
  /* #164: @18 = (@18-@0) */
  w18 -= w0;
  /* #165: @0 = (@5*@6) */
  w0  = (w5*w6);
  /* #166: @18 = (@18+@0) */
  w18 += w0;
  /* #167: @0 = (@7*@33) */
  w0  = (w7*w33);
  /* #168: @18 = (@18-@0) */
  w18 -= w0;
  /* #169: @18 = (@18+@14) */
  w18 += w14;
  /* #170: output[1][8] = @18 */
  if (res[1]) res[1][8] = w18;
  /* #171: @18 = (@7*@17) */
  w18  = (w7*w17);
  /* #172: @14 = (@5*@13) */
  w14  = (w5*w13);
  /* #173: @18 = (@18+@14) */
  w18 += w14;
  /* #174: @14 = (@3*@6) */
  w14  = (w3*w6);
  /* #175: @18 = (@18-@14) */
  w18 -= w14;
  /* #176: @14 = (@8*@33) */
  w14  = (w8*w33);
  /* #177: @18 = (@18-@14) */
  w18 -= w14;
  /* #178: @18 = (@18+@12) */
  w18 += w12;
  /* #179: output[1][9] = @18 */
  if (res[1]) res[1][9] = w18;
  /* #180: @17 = (@5*@17) */
  w17  = (w5*w17);
  /* #181: @13 = (@7*@13) */
  w13  = (w7*w13);
  /* #182: @17 = (@17-@13) */
  w17 -= w13;
  /* #183: @6 = (@8*@6) */
  w6  = (w8*w6);
  /* #184: @17 = (@17+@6) */
  w17 += w6;
  /* #185: @33 = (@3*@33) */
  w33  = (w3*w33);
  /* #186: @17 = (@17-@33) */
  w17 -= w33;
  /* #187: @17 = (@17+@9) */
  w17 += w9;
  /* #188: output[1][10] = @17 */
  if (res[1]) res[1][10] = w17;
  /* #189: output[1][11] = @10 */
  if (res[1]) res[1][11] = w10;
  /* #190: output[1][12] = @11 */
  if (res[1]) res[1][12] = w11;
  /* #191: output[1][13] = @15 */
  if (res[1]) res[1][13] = w15;
  /* #192: output[1][14] = @16 */
  if (res[1]) res[1][14] = w16;
  /* #193: @34 = zeros(15x15,41nz) */
  casadi_clear(w34, 41);
  /* #194: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #195: @35 = ones(15x1,7nz) */
  casadi_fill(w35, 7, 1.);
  /* #196: {@16, NULL, NULL, NULL, @15, NULL, NULL, @11, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@35) */
  w16 = w35[0];
  w15 = w35[1];
  w11 = w35[2];
  /* #197: @36 = 00 */
  /* #198: @37 = 00 */
  /* #199: @38 = 00 */
  /* #200: @10 = vertcat(@16, @36, @37, @38) */
  rr=(&w10);
  *rr++ = w16;
  /* #201: @16 = @10' */
  casadi_copy((&w10), 1, (&w16));
  /* #202: @24 = mac(@16,@27,@24) */
  casadi_mtimes((&w16), casadi_s2, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #203: @24 = @24' */
  /* #204: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #205: @10 = @10' */
  /* #206: @26 = mac(@10,@30,@26) */
  casadi_mtimes((&w10), casadi_s2, w30, casadi_s1, w26, casadi_s0, w, 0);
  /* #207: @26 = @26' */
  /* #208: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #209: {@10, @16, @17, @9} = vertsplit(@24) */
  w10 = w24[0];
  w16 = w24[1];
  w17 = w24[2];
  w9 = w24[3];
  /* #210: @21 = zeros(11x1) */
  casadi_clear(w21, 11);
  /* #211: @29 = zeros(1x3) */
  casadi_clear(w29, 3);
  /* #212: @33 = @15[0] */
  for (rr=(&w33), ss=(&w15)+0; ss!=(&w15)+1; ss+=1) *rr++ = *ss;
  /* #213: @33 = (-@33) */
  w33 = (- w33 );
  /* #214: @15 = @33' */
  casadi_copy((&w33), 1, (&w15));
  /* #215: @29 = mac(@15,@23,@29) */
  casadi_mtimes((&w15), casadi_s5, w23, casadi_s4, w29, casadi_s3, w, 0);
  /* #216: @29 = @29' */
  /* #217: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #218: @33 = @33' */
  /* #219: @22 = mac(@33,@32,@22) */
  casadi_mtimes((&w33), casadi_s5, w32, casadi_s4, w22, casadi_s3, w, 0);
  /* #220: @22 = @22' */
  /* #221: @29 = (@29+@22) */
  for (i=0, rr=w29, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #222: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #223: (@21[:3] += @29) */
  for (rr=w21+0, ss=w29; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #224: {@33, @15, @6, @13, @18, @12, @14, @0, @2, @39, @40} = vertsplit(@21) */
  w33 = w21[0];
  w15 = w21[1];
  w6 = w21[2];
  w13 = w21[3];
  w18 = w21[4];
  w12 = w21[5];
  w14 = w21[6];
  w0 = w21[7];
  w2 = w21[8];
  w39 = w21[9];
  w40 = w21[10];
  /* #225: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #226: @41 = (@5*@11) */
  w41  = (w5*w11);
  /* #227: @42 = (@7*@11) */
  w42  = (w7*w11);
  /* #228: @43 = (@8*@11) */
  w43  = (w8*w11);
  /* #229: @11 = (@3*@11) */
  w11  = (w3*w11);
  /* #230: @26 = vertcat(@41, @42, @43, @11) */
  rr=w26;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w11;
  /* #231: @29 = @26[1:4] */
  for (rr=w29, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #232: @29 = @29' */
  /* #233: @29 = (@4*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #234: @29 = @29' */
  /* #235: (@24[1:4] += @29) */
  for (rr=w24+1, ss=w29; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #236: @29 = @26[1:4] */
  for (rr=w29, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #237: @29 = @29' */
  /* #238: @29 = (@4*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #239: @29 = @29' */
  /* #240: (@24[1:4] += @29) */
  for (rr=w24+1, ss=w29; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #241: {@41, @42, @43, @11} = vertsplit(@24) */
  w41 = w24[0];
  w42 = w24[1];
  w43 = w24[2];
  w11 = w24[3];
  /* #242: @44 = (@3*@11) */
  w44  = (w3*w11);
  /* #243: @45 = (@8*@43) */
  w45  = (w8*w43);
  /* #244: @44 = (@44+@45) */
  w44 += w45;
  /* #245: @45 = (@7*@42) */
  w45  = (w7*w42);
  /* #246: @44 = (@44+@45) */
  w44 += w45;
  /* #247: @45 = (@5*@41) */
  w45  = (w5*w41);
  /* #248: @44 = (@44+@45) */
  w44 += w45;
  /* #249: @44 = (@44+@13) */
  w44 += w13;
  /* #250: @13 = (@3*@43) */
  w13  = (w3*w43);
  /* #251: @45 = (@8*@11) */
  w45  = (w8*w11);
  /* #252: @13 = (@13-@45) */
  w13 -= w45;
  /* #253: @45 = (@5*@42) */
  w45  = (w5*w42);
  /* #254: @13 = (@13+@45) */
  w13 += w45;
  /* #255: @45 = (@7*@41) */
  w45  = (w7*w41);
  /* #256: @13 = (@13-@45) */
  w13 -= w45;
  /* #257: @13 = (@13+@18) */
  w13 += w18;
  /* #258: @18 = (@7*@11) */
  w18  = (w7*w11);
  /* #259: @45 = (@5*@43) */
  w45  = (w5*w43);
  /* #260: @18 = (@18+@45) */
  w18 += w45;
  /* #261: @45 = (@3*@42) */
  w45  = (w3*w42);
  /* #262: @18 = (@18-@45) */
  w18 -= w45;
  /* #263: @45 = (@8*@41) */
  w45  = (w8*w41);
  /* #264: @18 = (@18-@45) */
  w18 -= w45;
  /* #265: @18 = (@18+@12) */
  w18 += w12;
  /* #266: @11 = (@5*@11) */
  w11  = (w5*w11);
  /* #267: @43 = (@7*@43) */
  w43  = (w7*w43);
  /* #268: @11 = (@11-@43) */
  w11 -= w43;
  /* #269: @42 = (@8*@42) */
  w42  = (w8*w42);
  /* #270: @11 = (@11+@42) */
  w11 += w42;
  /* #271: @41 = (@3*@41) */
  w41  = (w3*w41);
  /* #272: @11 = (@11-@41) */
  w11 -= w41;
  /* #273: @11 = (@11+@14) */
  w11 += w14;
  /* #274: @46 = vertcat(@10, @16, @17, @9, @33, @15, @6, @44, @13, @18, @11, @0, @2, @39, @40) */
  rr=w46;
  *rr++ = w10;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w9;
  *rr++ = w33;
  *rr++ = w15;
  *rr++ = w6;
  *rr++ = w44;
  *rr++ = w13;
  *rr++ = w18;
  *rr++ = w11;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w39;
  *rr++ = w40;
  /* #275: @21 = @46[:11] */
  for (rr=w21, ss=w46+0; ss!=w46+11; ss+=1) *rr++ = *ss;
  /* #276: (@34[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @21) */
  for (cii=casadi_s6, rr=w34, ss=w21; cii!=casadi_s6+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #277: @21 = @46[:11] */
  for (rr=w21, ss=w46+0; ss!=w46+11; ss+=1) *rr++ = *ss;
  /* #278: (@34[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @21) */
  for (cii=casadi_s7, rr=w34, ss=w21; cii!=casadi_s7+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #279: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #280: @36 = 00 */
  /* #281: @29 = ones(15x1,3nz) */
  casadi_fill(w29, 3, 1.);
  /* #282: {NULL, @10, NULL, NULL, NULL, @16, NULL, NULL, @17, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@29) */
  w10 = w29[0];
  w16 = w29[1];
  w17 = w29[2];
  /* #283: @37 = 00 */
  /* #284: @38 = 00 */
  /* #285: @9 = vertcat(@36, @10, @37, @38) */
  rr=(&w9);
  *rr++ = w10;
  /* #286: @10 = @9' */
  casadi_copy((&w9), 1, (&w10));
  /* #287: @24 = mac(@10,@27,@24) */
  casadi_mtimes((&w10), casadi_s8, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #288: @24 = @24' */
  /* #289: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #290: @9 = @9' */
  /* #291: @26 = mac(@9,@30,@26) */
  casadi_mtimes((&w9), casadi_s8, w30, casadi_s1, w26, casadi_s0, w, 0);
  /* #292: @26 = @26' */
  /* #293: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #294: {@9, @10, @33, @15} = vertsplit(@24) */
  w9 = w24[0];
  w10 = w24[1];
  w33 = w24[2];
  w15 = w24[3];
  /* #295: @21 = zeros(11x1) */
  casadi_clear(w21, 11);
  /* #296: @29 = zeros(1x3) */
  casadi_clear(w29, 3);
  /* #297: @6 = @16[0] */
  for (rr=(&w6), ss=(&w16)+0; ss!=(&w16)+1; ss+=1) *rr++ = *ss;
  /* #298: @6 = (-@6) */
  w6 = (- w6 );
  /* #299: @16 = @6' */
  casadi_copy((&w6), 1, (&w16));
  /* #300: @29 = mac(@16,@23,@29) */
  casadi_mtimes((&w16), casadi_s9, w23, casadi_s4, w29, casadi_s3, w, 0);
  /* #301: @29 = @29' */
  /* #302: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #303: @6 = @6' */
  /* #304: @22 = mac(@6,@32,@22) */
  casadi_mtimes((&w6), casadi_s9, w32, casadi_s4, w22, casadi_s3, w, 0);
  /* #305: @22 = @22' */
  /* #306: @29 = (@29+@22) */
  for (i=0, rr=w29, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #307: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #308: (@21[:3] += @29) */
  for (rr=w21+0, ss=w29; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #309: {@6, @16, @44, @13, @18, @11, @0, @2, @39, @40, @14} = vertsplit(@21) */
  w6 = w21[0];
  w16 = w21[1];
  w44 = w21[2];
  w13 = w21[3];
  w18 = w21[4];
  w11 = w21[5];
  w0 = w21[6];
  w2 = w21[7];
  w39 = w21[8];
  w40 = w21[9];
  w14 = w21[10];
  /* #310: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #311: @41 = (@7*@17) */
  w41  = (w7*w17);
  /* #312: @41 = (-@41) */
  w41 = (- w41 );
  /* #313: @42 = (@5*@17) */
  w42  = (w5*w17);
  /* #314: @43 = (@3*@17) */
  w43  = (w3*w17);
  /* #315: @17 = (@8*@17) */
  w17  = (w8*w17);
  /* #316: @17 = (-@17) */
  w17 = (- w17 );
  /* #317: @26 = vertcat(@41, @42, @43, @17) */
  rr=w26;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w17;
  /* #318: @29 = @26[1:4] */
  for (rr=w29, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #319: @29 = @29' */
  /* #320: @29 = (@4*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #321: @29 = @29' */
  /* #322: (@24[1:4] += @29) */
  for (rr=w24+1, ss=w29; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #323: @29 = @26[1:4] */
  for (rr=w29, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #324: @29 = @29' */
  /* #325: @29 = (@4*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #326: @29 = @29' */
  /* #327: (@24[1:4] += @29) */
  for (rr=w24+1, ss=w29; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #328: {@41, @42, @43, @17} = vertsplit(@24) */
  w41 = w24[0];
  w42 = w24[1];
  w43 = w24[2];
  w17 = w24[3];
  /* #329: @12 = (@3*@17) */
  w12  = (w3*w17);
  /* #330: @45 = (@8*@43) */
  w45  = (w8*w43);
  /* #331: @12 = (@12+@45) */
  w12 += w45;
  /* #332: @45 = (@7*@42) */
  w45  = (w7*w42);
  /* #333: @12 = (@12+@45) */
  w12 += w45;
  /* #334: @45 = (@5*@41) */
  w45  = (w5*w41);
  /* #335: @12 = (@12+@45) */
  w12 += w45;
  /* #336: @12 = (@12+@13) */
  w12 += w13;
  /* #337: @13 = (@3*@43) */
  w13  = (w3*w43);
  /* #338: @45 = (@8*@17) */
  w45  = (w8*w17);
  /* #339: @13 = (@13-@45) */
  w13 -= w45;
  /* #340: @45 = (@5*@42) */
  w45  = (w5*w42);
  /* #341: @13 = (@13+@45) */
  w13 += w45;
  /* #342: @45 = (@7*@41) */
  w45  = (w7*w41);
  /* #343: @13 = (@13-@45) */
  w13 -= w45;
  /* #344: @13 = (@13+@18) */
  w13 += w18;
  /* #345: @18 = (@7*@17) */
  w18  = (w7*w17);
  /* #346: @45 = (@5*@43) */
  w45  = (w5*w43);
  /* #347: @18 = (@18+@45) */
  w18 += w45;
  /* #348: @45 = (@3*@42) */
  w45  = (w3*w42);
  /* #349: @18 = (@18-@45) */
  w18 -= w45;
  /* #350: @45 = (@8*@41) */
  w45  = (w8*w41);
  /* #351: @18 = (@18-@45) */
  w18 -= w45;
  /* #352: @18 = (@18+@11) */
  w18 += w11;
  /* #353: @17 = (@5*@17) */
  w17  = (w5*w17);
  /* #354: @43 = (@7*@43) */
  w43  = (w7*w43);
  /* #355: @17 = (@17-@43) */
  w17 -= w43;
  /* #356: @42 = (@8*@42) */
  w42  = (w8*w42);
  /* #357: @17 = (@17+@42) */
  w17 += w42;
  /* #358: @41 = (@3*@41) */
  w41  = (w3*w41);
  /* #359: @17 = (@17-@41) */
  w17 -= w41;
  /* #360: @17 = (@17+@0) */
  w17 += w0;
  /* #361: @46 = vertcat(@9, @10, @33, @15, @6, @16, @44, @12, @13, @18, @17, @2, @39, @40, @14) */
  rr=w46;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w33;
  *rr++ = w15;
  *rr++ = w6;
  *rr++ = w16;
  *rr++ = w44;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w18;
  *rr++ = w17;
  *rr++ = w2;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w14;
  /* #362: @21 = @46[:11] */
  for (rr=w21, ss=w46+0; ss!=w46+11; ss+=1) *rr++ = *ss;
  /* #363: (@34[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @21) */
  for (cii=casadi_s10, rr=w34, ss=w21; cii!=casadi_s10+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #364: @21 = @46[:11] */
  for (rr=w21, ss=w46+0; ss!=w46+11; ss+=1) *rr++ = *ss;
  /* #365: (@34[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @21) */
  for (cii=casadi_s11, rr=w34, ss=w21; cii!=casadi_s11+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #366: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #367: @36 = 00 */
  /* #368: @37 = 00 */
  /* #369: @29 = ones(15x1,3nz) */
  casadi_fill(w29, 3, 1.);
  /* #370: {NULL, NULL, @9, NULL, NULL, NULL, @10, NULL, NULL, @33, NULL, NULL, NULL, NULL, NULL} = vertsplit(@29) */
  w9 = w29[0];
  w10 = w29[1];
  w33 = w29[2];
  /* #371: @38 = 00 */
  /* #372: @15 = vertcat(@36, @37, @9, @38) */
  rr=(&w15);
  *rr++ = w9;
  /* #373: @9 = @15' */
  casadi_copy((&w15), 1, (&w9));
  /* #374: @24 = mac(@9,@27,@24) */
  casadi_mtimes((&w9), casadi_s12, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #375: @24 = @24' */
  /* #376: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #377: @15 = @15' */
  /* #378: @26 = mac(@15,@30,@26) */
  casadi_mtimes((&w15), casadi_s12, w30, casadi_s1, w26, casadi_s0, w, 0);
  /* #379: @26 = @26' */
  /* #380: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #381: {@15, @9, @6, @16} = vertsplit(@24) */
  w15 = w24[0];
  w9 = w24[1];
  w6 = w24[2];
  w16 = w24[3];
  /* #382: @21 = zeros(11x1) */
  casadi_clear(w21, 11);
  /* #383: @29 = zeros(1x3) */
  casadi_clear(w29, 3);
  /* #384: @44 = @10[0] */
  for (rr=(&w44), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #385: @44 = (-@44) */
  w44 = (- w44 );
  /* #386: @10 = @44' */
  casadi_copy((&w44), 1, (&w10));
  /* #387: @29 = mac(@10,@23,@29) */
  casadi_mtimes((&w10), casadi_s13, w23, casadi_s4, w29, casadi_s3, w, 0);
  /* #388: @29 = @29' */
  /* #389: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #390: @44 = @44' */
  /* #391: @22 = mac(@44,@32,@22) */
  casadi_mtimes((&w44), casadi_s13, w32, casadi_s4, w22, casadi_s3, w, 0);
  /* #392: @22 = @22' */
  /* #393: @29 = (@29+@22) */
  for (i=0, rr=w29, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #394: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #395: (@21[:3] += @29) */
  for (rr=w21+0, ss=w29; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #396: {@44, @10, @12, @13, @18, @17, @2, @39, @40, @14, @0} = vertsplit(@21) */
  w44 = w21[0];
  w10 = w21[1];
  w12 = w21[2];
  w13 = w21[3];
  w18 = w21[4];
  w17 = w21[5];
  w2 = w21[6];
  w39 = w21[7];
  w40 = w21[8];
  w14 = w21[9];
  w0 = w21[10];
  /* #397: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #398: @41 = (@8*@33) */
  w41  = (w8*w33);
  /* #399: @41 = (-@41) */
  w41 = (- w41 );
  /* #400: @42 = (@3*@33) */
  w42  = (w3*w33);
  /* #401: @42 = (-@42) */
  w42 = (- w42 );
  /* #402: @43 = (@5*@33) */
  w43  = (w5*w33);
  /* #403: @33 = (@7*@33) */
  w33  = (w7*w33);
  /* #404: @26 = vertcat(@41, @42, @43, @33) */
  rr=w26;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w33;
  /* #405: @29 = @26[1:4] */
  for (rr=w29, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #406: @29 = @29' */
  /* #407: @29 = (@4*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #408: @29 = @29' */
  /* #409: (@24[1:4] += @29) */
  for (rr=w24+1, ss=w29; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #410: @29 = @26[1:4] */
  for (rr=w29, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #411: @29 = @29' */
  /* #412: @29 = (@4*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #413: @29 = @29' */
  /* #414: (@24[1:4] += @29) */
  for (rr=w24+1, ss=w29; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #415: {@41, @42, @43, @33} = vertsplit(@24) */
  w41 = w24[0];
  w42 = w24[1];
  w43 = w24[2];
  w33 = w24[3];
  /* #416: @11 = (@3*@33) */
  w11  = (w3*w33);
  /* #417: @45 = (@8*@43) */
  w45  = (w8*w43);
  /* #418: @11 = (@11+@45) */
  w11 += w45;
  /* #419: @45 = (@7*@42) */
  w45  = (w7*w42);
  /* #420: @11 = (@11+@45) */
  w11 += w45;
  /* #421: @45 = (@5*@41) */
  w45  = (w5*w41);
  /* #422: @11 = (@11+@45) */
  w11 += w45;
  /* #423: @11 = (@11+@13) */
  w11 += w13;
  /* #424: @13 = (@3*@43) */
  w13  = (w3*w43);
  /* #425: @45 = (@8*@33) */
  w45  = (w8*w33);
  /* #426: @13 = (@13-@45) */
  w13 -= w45;
  /* #427: @45 = (@5*@42) */
  w45  = (w5*w42);
  /* #428: @13 = (@13+@45) */
  w13 += w45;
  /* #429: @45 = (@7*@41) */
  w45  = (w7*w41);
  /* #430: @13 = (@13-@45) */
  w13 -= w45;
  /* #431: @13 = (@13+@18) */
  w13 += w18;
  /* #432: @18 = (@7*@33) */
  w18  = (w7*w33);
  /* #433: @45 = (@5*@43) */
  w45  = (w5*w43);
  /* #434: @18 = (@18+@45) */
  w18 += w45;
  /* #435: @45 = (@3*@42) */
  w45  = (w3*w42);
  /* #436: @18 = (@18-@45) */
  w18 -= w45;
  /* #437: @45 = (@8*@41) */
  w45  = (w8*w41);
  /* #438: @18 = (@18-@45) */
  w18 -= w45;
  /* #439: @18 = (@18+@17) */
  w18 += w17;
  /* #440: @33 = (@5*@33) */
  w33  = (w5*w33);
  /* #441: @43 = (@7*@43) */
  w43  = (w7*w43);
  /* #442: @33 = (@33-@43) */
  w33 -= w43;
  /* #443: @42 = (@8*@42) */
  w42  = (w8*w42);
  /* #444: @33 = (@33+@42) */
  w33 += w42;
  /* #445: @41 = (@3*@41) */
  w41  = (w3*w41);
  /* #446: @33 = (@33-@41) */
  w33 -= w41;
  /* #447: @33 = (@33+@2) */
  w33 += w2;
  /* #448: @46 = vertcat(@15, @9, @6, @16, @44, @10, @12, @11, @13, @18, @33, @39, @40, @14, @0) */
  rr=w46;
  *rr++ = w15;
  *rr++ = w9;
  *rr++ = w6;
  *rr++ = w16;
  *rr++ = w44;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w18;
  *rr++ = w33;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w14;
  *rr++ = w0;
  /* #449: @21 = @46[:11] */
  for (rr=w21, ss=w46+0; ss!=w46+11; ss+=1) *rr++ = *ss;
  /* #450: (@34[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @21) */
  for (cii=casadi_s14, rr=w34, ss=w21; cii!=casadi_s14+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #451: @21 = @46[:11] */
  for (rr=w21, ss=w46+0; ss!=w46+11; ss+=1) *rr++ = *ss;
  /* #452: (@34[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @21) */
  for (cii=casadi_s15, rr=w34, ss=w21; cii!=casadi_s15+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #453: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #454: @36 = 00 */
  /* #455: @37 = 00 */
  /* #456: @38 = 00 */
  /* #457: @47 = ones(15x1,2nz) */
  casadi_fill(w47, 2, 1.);
  /* #458: {NULL, NULL, NULL, @15, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL} = vertsplit(@47) */
  w15 = w47[0];
  w9 = w47[1];
  /* #459: @6 = vertcat(@36, @37, @38, @15) */
  rr=(&w6);
  *rr++ = w15;
  /* #460: @15 = @6' */
  casadi_copy((&w6), 1, (&w15));
  /* #461: @24 = mac(@15,@27,@24) */
  casadi_mtimes((&w15), casadi_s16, w27, casadi_s1, w24, casadi_s0, w, 0);
  /* #462: @24 = @24' */
  /* #463: @26 = zeros(1x4) */
  casadi_clear(w26, 4);
  /* #464: @6 = @6' */
  /* #465: @26 = mac(@6,@30,@26) */
  casadi_mtimes((&w6), casadi_s16, w30, casadi_s1, w26, casadi_s0, w, 0);
  /* #466: @26 = @26' */
  /* #467: @24 = (@24+@26) */
  for (i=0, rr=w24, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #468: {@6, @15, @16, @44} = vertsplit(@24) */
  w6 = w24[0];
  w15 = w24[1];
  w16 = w24[2];
  w44 = w24[3];
  /* #469: @36 = 00 */
  /* #470: @37 = 00 */
  /* #471: @38 = 00 */
  /* #472: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #473: @10 = (@3*@9) */
  w10  = (w3*w9);
  /* #474: @10 = (-@10) */
  w10 = (- w10 );
  /* #475: @12 = (@8*@9) */
  w12  = (w8*w9);
  /* #476: @11 = (@7*@9) */
  w11  = (w7*w9);
  /* #477: @11 = (-@11) */
  w11 = (- w11 );
  /* #478: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #479: @26 = vertcat(@10, @12, @11, @9) */
  rr=w26;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w9;
  /* #480: @29 = @26[1:4] */
  for (rr=w29, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #481: @29 = @29' */
  /* #482: @29 = (@4*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #483: @29 = @29' */
  /* #484: (@24[1:4] += @29) */
  for (rr=w24+1, ss=w29; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #485: @29 = @26[1:4] */
  for (rr=w29, ss=w26+1; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #486: @29 = @29' */
  /* #487: @29 = (@4*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #488: @29 = @29' */
  /* #489: (@24[1:4] += @29) */
  for (rr=w24+1, ss=w29; rr!=w24+4; rr+=1) *rr += *ss++;
  /* #490: {@4, @10, @12, @11} = vertsplit(@24) */
  w4 = w24[0];
  w10 = w24[1];
  w12 = w24[2];
  w11 = w24[3];
  /* #491: @9 = (@3*@11) */
  w9  = (w3*w11);
  /* #492: @13 = (@8*@12) */
  w13  = (w8*w12);
  /* #493: @9 = (@9+@13) */
  w9 += w13;
  /* #494: @13 = (@7*@10) */
  w13  = (w7*w10);
  /* #495: @9 = (@9+@13) */
  w9 += w13;
  /* #496: @13 = (@5*@4) */
  w13  = (w5*w4);
  /* #497: @9 = (@9+@13) */
  w9 += w13;
  /* #498: @13 = (@3*@12) */
  w13  = (w3*w12);
  /* #499: @18 = (@8*@11) */
  w18  = (w8*w11);
  /* #500: @13 = (@13-@18) */
  w13 -= w18;
  /* #501: @18 = (@5*@10) */
  w18  = (w5*w10);
  /* #502: @13 = (@13+@18) */
  w13 += w18;
  /* #503: @18 = (@7*@4) */
  w18  = (w7*w4);
  /* #504: @13 = (@13-@18) */
  w13 -= w18;
  /* #505: @18 = (@7*@11) */
  w18  = (w7*w11);
  /* #506: @33 = (@5*@12) */
  w33  = (w5*w12);
  /* #507: @18 = (@18+@33) */
  w18 += w33;
  /* #508: @33 = (@3*@10) */
  w33  = (w3*w10);
  /* #509: @18 = (@18-@33) */
  w18 -= w33;
  /* #510: @33 = (@8*@4) */
  w33  = (w8*w4);
  /* #511: @18 = (@18-@33) */
  w18 -= w33;
  /* #512: @5 = (@5*@11) */
  w5 *= w11;
  /* #513: @7 = (@7*@12) */
  w7 *= w12;
  /* #514: @5 = (@5-@7) */
  w5 -= w7;
  /* #515: @8 = (@8*@10) */
  w8 *= w10;
  /* #516: @5 = (@5+@8) */
  w5 += w8;
  /* #517: @3 = (@3*@4) */
  w3 *= w4;
  /* #518: @5 = (@5-@3) */
  w5 -= w3;
  /* #519: @48 = 00 */
  /* #520: @49 = 00 */
  /* #521: @50 = 00 */
  /* #522: @51 = 00 */
  /* #523: @52 = vertcat(@6, @15, @16, @44, @36, @37, @38, @9, @13, @18, @5, @48, @49, @50, @51) */
  rr=w52;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w44;
  *rr++ = w9;
  *rr++ = w13;
  *rr++ = w18;
  *rr++ = w5;
  /* #524: @53 = @52[:8] */
  for (rr=w53, ss=w52+0; ss!=w52+8; ss+=1) *rr++ = *ss;
  /* #525: (@34[:50:25;12:16] = @53) */
  for (rr=w34+0, ss=w53; rr!=w34+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *ss++;
  /* #526: @53 = @52[:8] */
  for (rr=w53, ss=w52+0; ss!=w52+8; ss+=1) *rr++ = *ss;
  /* #527: (@34[:50:25;3:19:4] = @53) */
  for (rr=w34+0, ss=w53; rr!=w34+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *ss++;
  /* #528: @54 = @34' */
  casadi_trans(w34,casadi_s17, w54, casadi_s17, iw);
  /* #529: output[2][0] = @54 */
  casadi_copy(w54, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s19;
    case 2: return casadi_s20;
    case 3: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s22;
    case 1: return casadi_s23;
    case 2: return casadi_s17;
    case 3: return casadi_s20;
    case 4: return casadi_s24;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 20;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 258;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
