/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s6[16] = {1, 11, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s8[51] = {11, 4, 0, 11, 22, 33, 44, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s10[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s12[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s13[6] = {11, 1, 0, 2, 0, 1};
static const casadi_int casadi_s14[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s15[3] = {0, 0, 0};
static const casadi_int casadi_s16[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s17[6] = {2, 1, 0, 2, 0, 1};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_constr_h_fun:(i0[11],i1[4],i2[],i3[17])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+12, w2, w3, w4, *w5=w+17, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+35, *w15=w+37, *w16=w+48, *w17=w+69, *w18=w+78, *w19=w+87, w20, w21, w22, *w23=w+99, w24, *w25=w+104, w26, *w27=w+109, *w28=w+118, *w29=w+121, *w30=w+154, *w31=w+187, w32, w33, w34, w35, w36, w37, *w38=w+205, *w39=w+209, *w40=w+213, *w41=w+217, *w42=w+221, *w43=w+237, *w44=w+253, *w45=w+297, *w46=w+341, *w47=w+369, *w48=w+385, *w49=w+401, *w50=w+445, *w51=w+566, w52, w53, *w54=w+689, *w55=w+700, *w59=w+711, *w60=w+722, w61, w62, w63, w64, w65, w66, w67, *w68=w+740, *w69=w+861, *w70=w+870, *w71=w+879, *w72=w+923;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(11x1,2nz) */
  casadi_clear(w1, 2);
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[3][15] */
  w3 = arg[3] ? arg[3][15] : 0;
  /* #4: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #5: @4 = (2.*@3) */
  w4 = (2.* w3 );
  /* #6: @5 = ones(11x1,10nz) */
  casadi_fill(w5, 10, 1.);
  /* #7: {@6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w6 = w5[0];
  /* #8: @4 = (@4*@6) */
  w4 *= w6;
  /* #9: @7 = sq(@3) */
  w7 = casadi_sq( w3 );
  /* #10: @8 = input[0][1] */
  w8 = arg[0] ? arg[0][1] : 0;
  /* #11: @9 = input[3][16] */
  w9 = arg[3] ? arg[3][16] : 0;
  /* #12: @9 = (@8-@9) */
  w9  = (w8-w9);
  /* #13: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #14: @7 = (@7+@10) */
  w7 += w10;
  /* #15: @7 = sqrt(@7) */
  w7 = sqrt( w7 );
  /* #16: @10 = (2.*@7) */
  w10 = (2.* w7 );
  /* #17: @4 = (@4/@10) */
  w4 /= w10;
  /* #18: (@1[0] = @4) */
  for (rr=w1+0, ss=(&w4); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #19: @11 = (2.*@9) */
  w11 = (2.* w9 );
  /* #20: @12 = ones(11x1,1nz) */
  w12 = 1.;
  /* #21: {NULL, @13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@12) */
  w13 = w12;
  /* #22: @11 = (@11*@13) */
  w11 *= w13;
  /* #23: @11 = (@11/@10) */
  w11 /= w10;
  /* #24: (@1[1] = @11) */
  for (rr=w1+1, ss=(&w11); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #25: @14 = @1' */
  casadi_copy(w1, 2, w14);
  /* #26: @15 = zeros(11x1) */
  casadi_clear(w15, 11);
  /* #27: @16 = zeros(3x7) */
  casadi_clear(w16, 21);
  /* #28: @17 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w17);
  /* #29: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #30: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #31: @12 = input[0][3] */
  w12 = arg[0] ? arg[0][3] : 0;
  /* #32: @20 = input[0][4] */
  w20 = arg[0] ? arg[0][4] : 0;
  /* #33: @21 = input[0][5] */
  w21 = arg[0] ? arg[0][5] : 0;
  /* #34: @22 = input[0][6] */
  w22 = arg[0] ? arg[0][6] : 0;
  /* #35: @23 = vertcat(@12, @20, @21, @22) */
  rr=w23;
  *rr++ = w12;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  /* #36: @24 = ||@23||_F */
  w24 = sqrt(casadi_dot(4, w23, w23));
  /* #37: @25 = (@23/@24) */
  for (i=0, rr=w25, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)/w24);
  /* #38: @26 = @25[3] */
  for (rr=(&w26), ss=w25+3; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #39: @26 = (-@26) */
  w26 = (- w26 );
  /* #40: (@19[3] = @26) */
  for (rr=w19+3, ss=(&w26); rr!=w19+4; rr+=1) *rr = *ss++;
  /* #41: @26 = @25[2] */
  for (rr=(&w26), ss=w25+2; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #42: (@19[6] = @26) */
  for (rr=w19+6, ss=(&w26); rr!=w19+7; rr+=1) *rr = *ss++;
  /* #43: @26 = @25[1] */
  for (rr=(&w26), ss=w25+1; ss!=w25+2; ss+=1) *rr++ = *ss;
  /* #44: @26 = (-@26) */
  w26 = (- w26 );
  /* #45: (@19[7] = @26) */
  for (rr=w19+7, ss=(&w26); rr!=w19+8; rr+=1) *rr = *ss++;
  /* #46: @26 = @25[3] */
  for (rr=(&w26), ss=w25+3; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #47: (@19[1] = @26) */
  for (rr=w19+1, ss=(&w26); rr!=w19+2; rr+=1) *rr = *ss++;
  /* #48: @26 = @25[2] */
  for (rr=(&w26), ss=w25+2; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #49: @26 = (-@26) */
  w26 = (- w26 );
  /* #50: (@19[2] = @26) */
  for (rr=w19+2, ss=(&w26); rr!=w19+3; rr+=1) *rr = *ss++;
  /* #51: @26 = @25[1] */
  for (rr=(&w26), ss=w25+1; ss!=w25+2; ss+=1) *rr++ = *ss;
  /* #52: (@19[5] = @26) */
  for (rr=w19+5, ss=(&w26); rr!=w19+6; rr+=1) *rr = *ss++;
  /* #53: @27 = (2.*@19) */
  for (i=0, rr=w27, cs=w19; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #54: @18 = mac(@27,@19,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #55: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #56: @26 = @25[0] */
  for (rr=(&w26), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #57: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #58: @18 = (@26*@19) */
  for (i=0, rr=w18, cs=w19; i<9; ++i) (*rr++)  = (w26*(*cs++));
  /* #59: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #60: @28 = zeros(3x1) */
  casadi_clear(w28, 3);
  /* #61: @29 = horzcat(@16, @17, @28) */
  rr=w29;
  for (i=0, cs=w16; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #62: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #63: @31 = zeros(4x3) */
  casadi_clear(w31, 12);
  /* #64: @32 = 0.5 */
  w32 = 5.0000000000000000e-01;
  /* #65: @33 = 0 */
  w33 = 0.;
  /* #66: @34 = 0 */
  w34 = 0.;
  /* #67: @35 = 0 */
  w35 = 0.;
  /* #68: @36 = input[0][10] */
  w36 = arg[0] ? arg[0][10] : 0;
  /* #69: @37 = (-@36) */
  w37 = (- w36 );
  /* #70: @38 = horzcat(@33, @34, @35, @37) */
  rr=w38;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w37;
  /* #71: @38 = @38' */
  /* #72: @33 = 0 */
  w33 = 0.;
  /* #73: @34 = 0 */
  w34 = 0.;
  /* #74: @35 = 0 */
  w35 = 0.;
  /* #75: @39 = horzcat(@33, @34, @36, @35) */
  rr=w39;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w36;
  *rr++ = w35;
  /* #76: @39 = @39' */
  /* #77: @33 = 0 */
  w33 = 0.;
  /* #78: @34 = (-@36) */
  w34 = (- w36 );
  /* #79: @35 = 0 */
  w35 = 0.;
  /* #80: @37 = 0 */
  w37 = 0.;
  /* #81: @40 = horzcat(@33, @34, @35, @37) */
  rr=w40;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w37;
  /* #82: @40 = @40' */
  /* #83: @33 = 0 */
  w33 = 0.;
  /* #84: @34 = 0 */
  w34 = 0.;
  /* #85: @35 = 0 */
  w35 = 0.;
  /* #86: @41 = horzcat(@36, @33, @34, @35) */
  rr=w41;
  *rr++ = w36;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  /* #87: @41 = @41' */
  /* #88: @42 = horzcat(@38, @39, @40, @41) */
  rr=w42;
  for (i=0, cs=w38; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<4; ++i) *rr++ = *cs++;
  /* #89: @43 = @42' */
  for (i=0, rr=w43, cs=w42; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #90: @43 = (@32*@43) */
  for (i=0, rr=w43, cs=w43; i<16; ++i) (*rr++)  = (w32*(*cs++));
  /* #91: @42 = zeros(4x4) */
  casadi_clear(w42, 16);
  /* #92: @44 = horzcat(@31, @43, @42) */
  rr=w44;
  for (i=0, cs=w31; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<16; ++i) *rr++ = *cs++;
  /* #93: @45 = @44' */
  for (i=0, rr=w45, cs=w44; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #94: @46 = zeros(4x7) */
  casadi_clear(w46, 28);
  /* #95: @43 = zeros(4x4) */
  casadi_clear(w43, 16);
  /* #96: @42 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w42);
  /* #97: @47 = zeros(4x4) */
  casadi_clear(w47, 16);
  /* #98: @33 = 0.6756 */
  w33 = 6.7559999999999998e-01;
  /* #99: (@47[0] = @33) */
  for (rr=w47+0, ss=(&w33); rr!=w47+1; rr+=1) *rr = *ss++;
  /* #100: @33 = 0 */
  w33 = 0.;
  /* #101: (@47[4] = @33) */
  for (rr=w47+4, ss=(&w33); rr!=w47+5; rr+=1) *rr = *ss++;
  /* #102: @33 = 0 */
  w33 = 0.;
  /* #103: (@47[8] = @33) */
  for (rr=w47+8, ss=(&w33); rr!=w47+9; rr+=1) *rr = *ss++;
  /* #104: @33 = 0 */
  w33 = 0.;
  /* #105: (@47[12] = @33) */
  for (rr=w47+12, ss=(&w33); rr!=w47+13; rr+=1) *rr = *ss++;
  /* #106: @33 = 0 */
  w33 = 0.;
  /* #107: (@47[1] = @33) */
  for (rr=w47+1, ss=(&w33); rr!=w47+2; rr+=1) *rr = *ss++;
  /* #108: @33 = 0.6344 */
  w33 = 6.3439999999999996e-01;
  /* #109: (@47[5] = @33) */
  for (rr=w47+5, ss=(&w33); rr!=w47+6; rr+=1) *rr = *ss++;
  /* #110: @33 = 0 */
  w33 = 0.;
  /* #111: (@47[9] = @33) */
  for (rr=w47+9, ss=(&w33); rr!=w47+10; rr+=1) *rr = *ss++;
  /* #112: @33 = 0 */
  w33 = 0.;
  /* #113: (@47[13] = @33) */
  for (rr=w47+13, ss=(&w33); rr!=w47+14; rr+=1) *rr = *ss++;
  /* #114: @33 = 0 */
  w33 = 0.;
  /* #115: (@47[2] = @33) */
  for (rr=w47+2, ss=(&w33); rr!=w47+3; rr+=1) *rr = *ss++;
  /* #116: @33 = 0 */
  w33 = 0.;
  /* #117: (@47[6] = @33) */
  for (rr=w47+6, ss=(&w33); rr!=w47+7; rr+=1) *rr = *ss++;
  /* #118: @33 = 0.408 */
  w33 = 4.0799999999999997e-01;
  /* #119: (@47[10] = @33) */
  for (rr=w47+10, ss=(&w33); rr!=w47+11; rr+=1) *rr = *ss++;
  /* #120: @33 = 0 */
  w33 = 0.;
  /* #121: (@47[14] = @33) */
  for (rr=w47+14, ss=(&w33); rr!=w47+15; rr+=1) *rr = *ss++;
  /* #122: @33 = 0 */
  w33 = 0.;
  /* #123: (@47[3] = @33) */
  for (rr=w47+3, ss=(&w33); rr!=w47+4; rr+=1) *rr = *ss++;
  /* #124: @33 = 0 */
  w33 = 0.;
  /* #125: (@47[7] = @33) */
  for (rr=w47+7, ss=(&w33); rr!=w47+8; rr+=1) *rr = *ss++;
  /* #126: @33 = 0 */
  w33 = 0.;
  /* #127: (@47[11] = @33) */
  for (rr=w47+11, ss=(&w33); rr!=w47+12; rr+=1) *rr = *ss++;
  /* #128: @33 = 0.2953 */
  w33 = 2.9530000000000001e-01;
  /* #129: (@47[15] = @33) */
  for (rr=w47+15, ss=(&w33); rr!=w47+16; rr+=1) *rr = *ss++;
  /* #130: @42 = (@47\@42) */
  rr = w42;
  ss = w47;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #131: @48 = zeros(4x4) */
  casadi_clear(w48, 16);
  /* #132: @33 = 0.5941 */
  w33 = 5.9409999999999996e-01;
  /* #133: (@48[0] = @33) */
  for (rr=w48+0, ss=(&w33); rr!=w48+1; rr+=1) *rr = *ss++;
  /* #134: @33 = -0.8109 */
  w33 = -8.1089999999999995e-01;
  /* #135: @34 = (@33*@36) */
  w34  = (w33*w36);
  /* #136: (@48[4] = @34) */
  for (rr=w48+4, ss=(&w34); rr!=w48+5; rr+=1) *rr = *ss++;
  /* #137: @34 = 0 */
  w34 = 0.;
  /* #138: (@48[8] = @34) */
  for (rr=w48+8, ss=(&w34); rr!=w48+9; rr+=1) *rr = *ss++;
  /* #139: @34 = 0 */
  w34 = 0.;
  /* #140: (@48[12] = @34) */
  for (rr=w48+12, ss=(&w34); rr!=w48+13; rr+=1) *rr = *ss++;
  /* #141: @34 = 0.3984 */
  w34 = 3.9839999999999998e-01;
  /* #142: @35 = (@34*@36) */
  w35  = (w34*w36);
  /* #143: (@48[1] = @35) */
  for (rr=w48+1, ss=(&w35); rr!=w48+2; rr+=1) *rr = *ss++;
  /* #144: @35 = 0.704 */
  w35 = 7.0399999999999996e-01;
  /* #145: (@48[5] = @35) */
  for (rr=w48+5, ss=(&w35); rr!=w48+6; rr+=1) *rr = *ss++;
  /* #146: @35 = 0 */
  w35 = 0.;
  /* #147: (@48[9] = @35) */
  for (rr=w48+9, ss=(&w35); rr!=w48+10; rr+=1) *rr = *ss++;
  /* #148: @35 = 0 */
  w35 = 0.;
  /* #149: (@48[13] = @35) */
  for (rr=w48+13, ss=(&w35); rr!=w48+14; rr+=1) *rr = *ss++;
  /* #150: @35 = 0 */
  w35 = 0.;
  /* #151: (@48[2] = @35) */
  for (rr=w48+2, ss=(&w35); rr!=w48+3; rr+=1) *rr = *ss++;
  /* #152: @35 = 0 */
  w35 = 0.;
  /* #153: (@48[6] = @35) */
  for (rr=w48+6, ss=(&w35); rr!=w48+7; rr+=1) *rr = *ss++;
  /* #154: @35 = 0.9365 */
  w35 = 9.3650000000000000e-01;
  /* #155: (@48[10] = @35) */
  for (rr=w48+10, ss=(&w35); rr!=w48+11; rr+=1) *rr = *ss++;
  /* #156: @35 = 0 */
  w35 = 0.;
  /* #157: (@48[14] = @35) */
  for (rr=w48+14, ss=(&w35); rr!=w48+15; rr+=1) *rr = *ss++;
  /* #158: @35 = 0 */
  w35 = 0.;
  /* #159: (@48[3] = @35) */
  for (rr=w48+3, ss=(&w35); rr!=w48+4; rr+=1) *rr = *ss++;
  /* #160: @35 = 0 */
  w35 = 0.;
  /* #161: (@48[7] = @35) */
  for (rr=w48+7, ss=(&w35); rr!=w48+8; rr+=1) *rr = *ss++;
  /* #162: @35 = 0 */
  w35 = 0.;
  /* #163: (@48[11] = @35) */
  for (rr=w48+11, ss=(&w35); rr!=w48+12; rr+=1) *rr = *ss++;
  /* #164: @35 = 0.9752 */
  w35 = 9.7519999999999996e-01;
  /* #165: (@48[15] = @35) */
  for (rr=w48+15, ss=(&w35); rr!=w48+16; rr+=1) *rr = *ss++;
  /* #166: @43 = mac(@42,@48,@43) */
  for (i=0, rr=w43; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w42+j, tt=w48+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #167: @43 = (-@43) */
  for (i=0, rr=w43, cs=w43; i<16; ++i) *rr++ = (- *cs++ );
  /* #168: @44 = horzcat(@46, @43) */
  rr=w44;
  for (i=0, cs=w46; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<16; ++i) *rr++ = *cs++;
  /* #169: @49 = @44' */
  for (i=0, rr=w49, cs=w44; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #170: @50 = horzcat(@30, @45, @49) */
  rr=w50;
  for (i=0, cs=w30; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<44; ++i) *rr++ = *cs++;
  /* #171: @51 = @50' */
  for (i=0, rr=w51, cs=w50; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #172: @35 = input[0][2] */
  w35 = arg[0] ? arg[0][2] : 0;
  /* #173: @37 = input[0][7] */
  w37 = arg[0] ? arg[0][7] : 0;
  /* #174: @52 = input[0][8] */
  w52 = arg[0] ? arg[0][8] : 0;
  /* #175: @53 = input[0][9] */
  w53 = arg[0] ? arg[0][9] : 0;
  /* #176: @54 = vertcat(@2, @8, @35, @12, @20, @21, @22, @37, @52, @53, @36) */
  rr=w54;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w35;
  *rr++ = w12;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w37;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w36;
  /* #177: @15 = mac(@51,@54,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w51+j, tt=w54+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #178: @55 = zeros(11x1) */
  casadi_clear(w55, 11);
  /* #179: @46 = zeros(4x7) */
  casadi_clear(w46, 28);
  /* #180: @43 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w43);
  /* #181: @43 = (@47\@43) */
  rr = w43;
  ss = w47;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #182: @47 = @43' */
  for (i=0, rr=w47, cs=w43; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #183: @45 = horzcat(@46, @47) */
  rr=w45;
  for (i=0, cs=w46; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<16; ++i) *rr++ = *cs++;
  /* #184: @49 = @45' */
  for (i=0, rr=w49, cs=w45; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #185: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #186: @8 = input[1][1] */
  w8 = arg[1] ? arg[1][1] : 0;
  /* #187: @35 = input[1][2] */
  w35 = arg[1] ? arg[1][2] : 0;
  /* #188: @12 = input[1][3] */
  w12 = arg[1] ? arg[1][3] : 0;
  /* #189: @38 = vertcat(@2, @8, @35, @12) */
  rr=w38;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w35;
  *rr++ = w12;
  /* #190: @55 = mac(@49,@38,@55) */
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w49+j, tt=w38+i*4; k<4; ++k) *rr += ss[k*11]**tt++;
  /* #191: @15 = (@15+@55) */
  for (i=0, rr=w15, cs=w55; i<11; ++i) (*rr++) += (*cs++);
  /* #192: @0 = mac(@14,@15,@0) */
  casadi_mtimes(w14, casadi_s6, w15, casadi_s5, (&w0), casadi_s4, w, 0);
  /* #193: @2 = 0 */
  w2 = 0.;
  /* #194: @39 = zeros(1x4) */
  casadi_clear(w39, 4);
  /* #195: @14 = zeros(11x1,2nz) */
  casadi_clear(w14, 2);
  /* #196: @8 = (2.*@3) */
  w8 = (2.* w3 );
  /* #197: @5 = ones(11x1,10nz) */
  casadi_fill(w5, 10, 1.);
  /* #198: {@35, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w35 = w5[0];
  /* #199: @8 = (@8*@35) */
  w8 *= w35;
  /* #200: @35 = (2.*@7) */
  w35 = (2.* w7 );
  /* #201: @8 = (@8/@35) */
  w8 /= w35;
  /* #202: (@14[0] = @8) */
  for (rr=w14+0, ss=(&w8); rr!=w14+1; rr+=1) *rr = *ss++;
  /* #203: @8 = (2.*@9) */
  w8 = (2.* w9 );
  /* #204: @12 = ones(11x1,1nz) */
  w12 = 1.;
  /* #205: {NULL, @20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@12) */
  w20 = w12;
  /* #206: @8 = (@8*@20) */
  w8 *= w20;
  /* #207: @8 = (@8/@35) */
  w8 /= w35;
  /* #208: (@14[1] = @8) */
  for (rr=w14+1, ss=(&w8); rr!=w14+2; rr+=1) *rr = *ss++;
  /* #209: @14 = @14' */
  /* #210: @45 = zeros(4x11) */
  casadi_clear(w45, 44);
  /* #211: @55 = zeros(11x1) */
  casadi_clear(w55, 11);
  /* #212: @8 = ones(4x1,1nz) */
  w8 = 1.;
  /* #213: {@35, NULL, NULL, NULL} = vertsplit(@8) */
  w35 = w8;
  /* #214: @56 = 00 */
  /* #215: @57 = 00 */
  /* #216: @58 = 00 */
  /* #217: @8 = vertcat(@35, @56, @57, @58) */
  rr=(&w8);
  *rr++ = w35;
  /* #218: @55 = mac(@49,@8,@55) */
  casadi_mtimes(w49, casadi_s8, (&w8), casadi_s7, w55, casadi_s5, w, 0);
  /* #219: (@45[:44:4] = @55) */
  for (rr=w45+0, ss=w55; rr!=w45+44; rr+=4) *rr = *ss++;
  /* #220: @55 = zeros(11x1) */
  casadi_clear(w55, 11);
  /* #221: @56 = 00 */
  /* #222: @8 = ones(4x1,1nz) */
  w8 = 1.;
  /* #223: {NULL, @35, NULL, NULL} = vertsplit(@8) */
  w35 = w8;
  /* #224: @57 = 00 */
  /* #225: @58 = 00 */
  /* #226: @8 = vertcat(@56, @35, @57, @58) */
  rr=(&w8);
  *rr++ = w35;
  /* #227: @55 = mac(@49,@8,@55) */
  casadi_mtimes(w49, casadi_s8, (&w8), casadi_s9, w55, casadi_s5, w, 0);
  /* #228: (@45[1:45:4] = @55) */
  for (rr=w45+1, ss=w55; rr!=w45+45; rr+=4) *rr = *ss++;
  /* #229: @55 = zeros(11x1) */
  casadi_clear(w55, 11);
  /* #230: @56 = 00 */
  /* #231: @57 = 00 */
  /* #232: @8 = ones(4x1,1nz) */
  w8 = 1.;
  /* #233: {NULL, NULL, @35, NULL} = vertsplit(@8) */
  w35 = w8;
  /* #234: @58 = 00 */
  /* #235: @8 = vertcat(@56, @57, @35, @58) */
  rr=(&w8);
  *rr++ = w35;
  /* #236: @55 = mac(@49,@8,@55) */
  casadi_mtimes(w49, casadi_s8, (&w8), casadi_s10, w55, casadi_s5, w, 0);
  /* #237: (@45[2:46:4] = @55) */
  for (rr=w45+2, ss=w55; rr!=w45+46; rr+=4) *rr = *ss++;
  /* #238: @55 = zeros(11x1) */
  casadi_clear(w55, 11);
  /* #239: @56 = 00 */
  /* #240: @57 = 00 */
  /* #241: @58 = 00 */
  /* #242: @8 = ones(4x1,1nz) */
  w8 = 1.;
  /* #243: {NULL, NULL, NULL, @35} = vertsplit(@8) */
  w35 = w8;
  /* #244: @8 = vertcat(@56, @57, @58, @35) */
  rr=(&w8);
  *rr++ = w35;
  /* #245: @55 = mac(@49,@8,@55) */
  casadi_mtimes(w49, casadi_s8, (&w8), casadi_s11, w55, casadi_s5, w, 0);
  /* #246: (@45[3:47:4] = @55) */
  for (rr=w45+3, ss=w55; rr!=w45+47; rr+=4) *rr = *ss++;
  /* #247: @49 = @45' */
  for (i=0, rr=w49, cs=w45; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #248: @39 = mac(@14,@49,@39) */
  casadi_mtimes(w14, casadi_s6, w49, casadi_s8, w39, casadi_s12, w, 0);
  /* #249: @2 = mac(@39,@38,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w38+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #250: @2 = (@0+@2) */
  w2  = (w0+w2);
  /* #251: @8 = 5 */
  w8 = 5.;
  /* #252: @35 = 0.8 */
  w35 = 8.0000000000000004e-01;
  /* #253: @35 = (@7-@35) */
  w35  = (w7-w35);
  /* #254: @8 = (@8*@35) */
  w8 *= w35;
  /* #255: @2 = (@2+@8) */
  w2 += w8;
  /* #256: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #257: @2 = 0 */
  w2 = 0.;
  /* #258: @55 = zeros(11x1) */
  casadi_clear(w55, 11);
  /* #259: @59 = zeros(11x1) */
  casadi_clear(w59, 11);
  /* #260: @60 = dense(@1) */
  casadi_densify(w1, casadi_s13, w60, 0);
  /* #261: @59 = mac(@50,@60,@59) */
  for (i=0, rr=w59; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w50+j, tt=w60+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #262: {@8, @20, @12, @21, @22, @37, @52, @53, @36, @61, @62} = vertsplit(@59) */
  w8 = w59[0];
  w20 = w59[1];
  w12 = w59[2];
  w21 = w59[3];
  w22 = w59[4];
  w37 = w59[5];
  w52 = w59[6];
  w53 = w59[7];
  w36 = w59[8];
  w61 = w59[9];
  w62 = w59[10];
  /* #263: @63 = (2.*@3) */
  w63 = (2.* w3 );
  /* #264: @64 = (@4/@10) */
  w64  = (w4/w10);
  /* #265: @65 = 0 */
  w65 = 0.;
  /* #266: @59 = @15; (@59[1] = @65) */
  casadi_copy(w15, 11, w59);
  for (rr=w59+1, ss=(&w65); rr!=w59+2; rr+=1) *rr = *ss++;
  /* #267: @65 = @59[0] */
  for (rr=(&w65), ss=w59+0; ss!=w59+1; ss+=1) *rr++ = *ss;
  /* #268: @64 = (@64*@65) */
  w64 *= w65;
  /* #269: @64 = (-@64) */
  w64 = (- w64 );
  /* #270: @66 = (@11/@10) */
  w66  = (w11/w10);
  /* #271: @67 = @15[1] */
  for (rr=(&w67), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #272: @66 = (@66*@67) */
  w66 *= w67;
  /* #273: @64 = (@64-@66) */
  w64 -= w66;
  /* #274: @64 = (2.*@64) */
  w64 = (2.* w64 );
  /* #275: @66 = (2.*@7) */
  w66 = (2.* w7 );
  /* #276: @64 = (@64/@66) */
  w64 /= w66;
  /* #277: @63 = (@63*@64) */
  w63 *= w64;
  /* #278: @65 = (@65/@10) */
  w65 /= w10;
  /* #279: @65 = (@6*@65) */
  w65  = (w6*w65);
  /* #280: @65 = (2.*@65) */
  w65 = (2.* w65 );
  /* #281: @63 = (@63+@65) */
  w63 += w65;
  /* #282: @8 = (@8+@63) */
  w8 += w63;
  /* #283: (@55[0] = @8) */
  for (rr=w55+0, ss=(&w8); rr!=w55+1; rr+=1) *rr = *ss++;
  /* #284: @67 = (@67/@10) */
  w67 /= w10;
  /* #285: @67 = (@13*@67) */
  w67  = (w13*w67);
  /* #286: @67 = (2.*@67) */
  w67 = (2.* w67 );
  /* #287: @8 = (2.*@9) */
  w8 = (2.* w9 );
  /* #288: @8 = (@8*@64) */
  w8 *= w64;
  /* #289: @67 = (@67+@8) */
  w67 += w8;
  /* #290: @20 = (@20+@67) */
  w20 += w67;
  /* #291: (@55[1] = @20) */
  for (rr=w55+1, ss=(&w20); rr!=w55+2; rr+=1) *rr = *ss++;
  /* #292: (@55[2] = @12) */
  for (rr=w55+2, ss=(&w12); rr!=w55+3; rr+=1) *rr = *ss++;
  /* #293: @39 = zeros(4x1) */
  casadi_clear(w39, 4);
  /* #294: @51 = zeros(11x11) */
  casadi_clear(w51, 121);
  /* #295: @59 = @54' */
  casadi_copy(w54, 11, w59);
  /* #296: @51 = mac(@60,@59,@51) */
  for (i=0, rr=w51; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w60+j, tt=w59+i*1; k<1; ++k) *rr += ss[k*11]**tt++;
  /* #297: @68 = @51' */
  for (i=0, rr=w68, cs=w51; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #298: {@30, @45, @44} = horzsplit(@68) */
  casadi_copy(w68, 33, w30);
  casadi_copy(w68+33, 44, w45);
  casadi_copy(w68+77, 44, w44);
  /* #299: @29 = @30' */
  for (i=0, rr=w29, cs=w30; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #300: {NULL, @17, NULL} = horzsplit(@29) */
  casadi_copy(w29+21, 9, w17);
  /* #301: @12 = dot(@19, @17) */
  w12 = casadi_dot(9, w19, w17);
  /* #302: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #303: (@39[0] += @12) */
  for (rr=w39+0, ss=(&w12); rr!=w39+1; rr+=1) *rr += *ss++;
  /* #304: @18 = (@26*@17) */
  for (i=0, rr=w18, cs=w17; i<9; ++i) (*rr++)  = (w26*(*cs++));
  /* #305: @69 = zeros(3x3) */
  casadi_clear(w69, 9);
  /* #306: @70 = @27' */
  for (i=0, rr=w70, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #307: @69 = mac(@70,@17,@69) */
  for (i=0, rr=w69; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w70+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #308: @18 = (@18+@69) */
  for (i=0, rr=w18, cs=w69; i<9; ++i) (*rr++) += (*cs++);
  /* #309: @69 = zeros(3x3) */
  casadi_clear(w69, 9);
  /* #310: @70 = @19' */
  for (i=0, rr=w70, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #311: @69 = mac(@17,@70,@69) */
  for (i=0, rr=w69; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w70+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #312: @69 = (2.*@69) */
  for (i=0, rr=w69, cs=w69; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #313: @18 = (@18+@69) */
  for (i=0, rr=w18, cs=w69; i<9; ++i) (*rr++) += (*cs++);
  /* #314: @12 = @18[5] */
  for (rr=(&w12), ss=w18+5; ss!=w18+6; ss+=1) *rr++ = *ss;
  /* #315: (@39[1] += @12) */
  for (rr=w39+1, ss=(&w12); rr!=w39+2; rr+=1) *rr += *ss++;
  /* #316: @12 = 0 */
  w12 = 0.;
  /* #317: (@18[5] = @12) */
  for (rr=w18+5, ss=(&w12); rr!=w18+6; rr+=1) *rr = *ss++;
  /* #318: @12 = @18[2] */
  for (rr=(&w12), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #319: @12 = (-@12) */
  w12 = (- w12 );
  /* #320: (@39[2] += @12) */
  for (rr=w39+2, ss=(&w12); rr!=w39+3; rr+=1) *rr += *ss++;
  /* #321: @12 = 0 */
  w12 = 0.;
  /* #322: (@18[2] = @12) */
  for (rr=w18+2, ss=(&w12); rr!=w18+3; rr+=1) *rr = *ss++;
  /* #323: @12 = @18[1] */
  for (rr=(&w12), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #324: (@39[3] += @12) */
  for (rr=w39+3, ss=(&w12); rr!=w39+4; rr+=1) *rr += *ss++;
  /* #325: @12 = 0 */
  w12 = 0.;
  /* #326: (@18[1] = @12) */
  for (rr=w18+1, ss=(&w12); rr!=w18+2; rr+=1) *rr = *ss++;
  /* #327: @12 = @18[7] */
  for (rr=(&w12), ss=w18+7; ss!=w18+8; ss+=1) *rr++ = *ss;
  /* #328: @12 = (-@12) */
  w12 = (- w12 );
  /* #329: (@39[1] += @12) */
  for (rr=w39+1, ss=(&w12); rr!=w39+2; rr+=1) *rr += *ss++;
  /* #330: @12 = 0 */
  w12 = 0.;
  /* #331: (@18[7] = @12) */
  for (rr=w18+7, ss=(&w12); rr!=w18+8; rr+=1) *rr = *ss++;
  /* #332: @12 = @18[6] */
  for (rr=(&w12), ss=w18+6; ss!=w18+7; ss+=1) *rr++ = *ss;
  /* #333: (@39[2] += @12) */
  for (rr=w39+2, ss=(&w12); rr!=w39+3; rr+=1) *rr += *ss++;
  /* #334: @12 = 0 */
  w12 = 0.;
  /* #335: (@18[6] = @12) */
  for (rr=w18+6, ss=(&w12); rr!=w18+7; rr+=1) *rr = *ss++;
  /* #336: @12 = @18[3] */
  for (rr=(&w12), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #337: @12 = (-@12) */
  w12 = (- w12 );
  /* #338: (@39[3] += @12) */
  for (rr=w39+3, ss=(&w12); rr!=w39+4; rr+=1) *rr += *ss++;
  /* #339: @40 = (@39/@24) */
  for (i=0, rr=w40, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)/w24);
  /* #340: @41 = (@25/@24) */
  for (i=0, rr=w41, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)/w24);
  /* #341: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<4; ++i) *rr++ = (- *cs++ );
  /* #342: @12 = dot(@41, @39) */
  w12 = casadi_dot(4, w41, w39);
  /* #343: @12 = (@12/@24) */
  w12 /= w24;
  /* #344: @41 = (@12*@23) */
  for (i=0, rr=w41, cs=w23; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #345: @40 = (@40+@41) */
  for (i=0, rr=w40, cs=w41; i<4; ++i) (*rr++) += (*cs++);
  /* #346: {@12, @20, @67, @8} = vertsplit(@40) */
  w12 = w40[0];
  w20 = w40[1];
  w67 = w40[2];
  w8 = w40[3];
  /* #347: @21 = (@21+@12) */
  w21 += w12;
  /* #348: (@55[3] = @21) */
  for (rr=w55+3, ss=(&w21); rr!=w55+4; rr+=1) *rr = *ss++;
  /* #349: @22 = (@22+@20) */
  w22 += w20;
  /* #350: (@55[4] = @22) */
  for (rr=w55+4, ss=(&w22); rr!=w55+5; rr+=1) *rr = *ss++;
  /* #351: @37 = (@37+@67) */
  w37 += w67;
  /* #352: (@55[5] = @37) */
  for (rr=w55+5, ss=(&w37); rr!=w55+6; rr+=1) *rr = *ss++;
  /* #353: @52 = (@52+@8) */
  w52 += w8;
  /* #354: (@55[6] = @52) */
  for (rr=w55+6, ss=(&w52); rr!=w55+7; rr+=1) *rr = *ss++;
  /* #355: (@55[7] = @53) */
  for (rr=w55+7, ss=(&w53); rr!=w55+8; rr+=1) *rr = *ss++;
  /* #356: (@55[8] = @36) */
  for (rr=w55+8, ss=(&w36); rr!=w55+9; rr+=1) *rr = *ss++;
  /* #357: (@55[9] = @61) */
  for (rr=w55+9, ss=(&w61); rr!=w55+10; rr+=1) *rr = *ss++;
  /* #358: @47 = zeros(4x4) */
  casadi_clear(w47, 16);
  /* #359: @43 = @42' */
  for (i=0, rr=w43, cs=w42; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #360: @71 = @44' */
  for (i=0, rr=w71, cs=w44; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #361: {NULL, @48} = horzsplit(@71) */
  casadi_copy(w71+28, 16, w48);
  /* #362: @48 = (-@48) */
  for (i=0, rr=w48, cs=w48; i<16; ++i) *rr++ = (- *cs++ );
  /* #363: @47 = mac(@43,@48,@47) */
  for (i=0, rr=w47; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w43+j, tt=w48+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #364: @61 = 0 */
  w61 = 0.;
  /* #365: (@47[15] = @61) */
  for (rr=w47+15, ss=(&w61); rr!=w47+16; rr+=1) *rr = *ss++;
  /* #366: @61 = 0 */
  w61 = 0.;
  /* #367: (@47[11] = @61) */
  for (rr=w47+11, ss=(&w61); rr!=w47+12; rr+=1) *rr = *ss++;
  /* #368: @61 = 0 */
  w61 = 0.;
  /* #369: (@47[7] = @61) */
  for (rr=w47+7, ss=(&w61); rr!=w47+8; rr+=1) *rr = *ss++;
  /* #370: @61 = 0 */
  w61 = 0.;
  /* #371: (@47[3] = @61) */
  for (rr=w47+3, ss=(&w61); rr!=w47+4; rr+=1) *rr = *ss++;
  /* #372: @61 = 0 */
  w61 = 0.;
  /* #373: (@47[14] = @61) */
  for (rr=w47+14, ss=(&w61); rr!=w47+15; rr+=1) *rr = *ss++;
  /* #374: @61 = 0 */
  w61 = 0.;
  /* #375: (@47[10] = @61) */
  for (rr=w47+10, ss=(&w61); rr!=w47+11; rr+=1) *rr = *ss++;
  /* #376: @61 = 0 */
  w61 = 0.;
  /* #377: (@47[6] = @61) */
  for (rr=w47+6, ss=(&w61); rr!=w47+7; rr+=1) *rr = *ss++;
  /* #378: @61 = 0 */
  w61 = 0.;
  /* #379: (@47[2] = @61) */
  for (rr=w47+2, ss=(&w61); rr!=w47+3; rr+=1) *rr = *ss++;
  /* #380: @61 = 0 */
  w61 = 0.;
  /* #381: (@47[13] = @61) */
  for (rr=w47+13, ss=(&w61); rr!=w47+14; rr+=1) *rr = *ss++;
  /* #382: @61 = 0 */
  w61 = 0.;
  /* #383: (@47[9] = @61) */
  for (rr=w47+9, ss=(&w61); rr!=w47+10; rr+=1) *rr = *ss++;
  /* #384: @61 = 0 */
  w61 = 0.;
  /* #385: (@47[5] = @61) */
  for (rr=w47+5, ss=(&w61); rr!=w47+6; rr+=1) *rr = *ss++;
  /* #386: @61 = @47[1] */
  for (rr=(&w61), ss=w47+1; ss!=w47+2; ss+=1) *rr++ = *ss;
  /* #387: @61 = (@34*@61) */
  w61  = (w34*w61);
  /* #388: @62 = (@62+@61) */
  w62 += w61;
  /* #389: @61 = 0 */
  w61 = 0.;
  /* #390: (@47[1] = @61) */
  for (rr=w47+1, ss=(&w61); rr!=w47+2; rr+=1) *rr = *ss++;
  /* #391: @61 = 0 */
  w61 = 0.;
  /* #392: (@47[12] = @61) */
  for (rr=w47+12, ss=(&w61); rr!=w47+13; rr+=1) *rr = *ss++;
  /* #393: @61 = 0 */
  w61 = 0.;
  /* #394: (@47[8] = @61) */
  for (rr=w47+8, ss=(&w61); rr!=w47+9; rr+=1) *rr = *ss++;
  /* #395: @61 = @47[4] */
  for (rr=(&w61), ss=w47+4; ss!=w47+5; ss+=1) *rr++ = *ss;
  /* #396: @61 = (@33*@61) */
  w61  = (w33*w61);
  /* #397: @62 = (@62+@61) */
  w62 += w61;
  /* #398: @71 = @45' */
  for (i=0, rr=w71, cs=w45; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #399: {NULL, @47, NULL} = horzsplit(@71) */
  casadi_copy(w71+12, 16, w47);
  /* #400: @47 = (@32*@47) */
  for (i=0, rr=w47, cs=w47; i<16; ++i) (*rr++)  = (w32*(*cs++));
  /* #401: @43 = @47' */
  for (i=0, rr=w43, cs=w47; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #402: {@40, @41, @39, @72} = horzsplit(@43) */
  casadi_copy(w43, 4, w40);
  casadi_copy(w43+4, 4, w41);
  casadi_copy(w43+8, 4, w39);
  casadi_copy(w43+12, 4, w72);
  /* #403: @72 = @72' */
  /* #404: {@61, NULL, NULL, NULL} = horzsplit(@72) */
  w61 = w72[0];
  /* #405: @62 = (@62+@61) */
  w62 += w61;
  /* #406: @39 = @39' */
  /* #407: {NULL, @61, NULL, NULL} = horzsplit(@39) */
  w61 = w39[1];
  /* #408: @62 = (@62-@61) */
  w62 -= w61;
  /* #409: @41 = @41' */
  /* #410: {NULL, NULL, @61, NULL} = horzsplit(@41) */
  w61 = w41[2];
  /* #411: @62 = (@62+@61) */
  w62 += w61;
  /* #412: @40 = @40' */
  /* #413: {NULL, NULL, NULL, @61} = horzsplit(@40) */
  w61 = w40[3];
  /* #414: @62 = (@62-@61) */
  w62 -= w61;
  /* #415: (@55[10] = @62) */
  for (rr=w55+10, ss=(&w62); rr!=w55+11; rr+=1) *rr = *ss++;
  /* #416: @55 = @55' */
  /* #417: @2 = mac(@55,@15,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w55+j, tt=w15+i*11; k<11; ++k) *rr += ss[k*1]**tt++;
  /* #418: @62 = 0 */
  w62 = 0.;
  /* #419: @40 = zeros(1x4) */
  casadi_clear(w40, 4);
  /* #420: @55 = zeros(11x1) */
  casadi_clear(w55, 11);
  /* #421: @60 = zeros(11x1) */
  casadi_clear(w60, 11);
  /* #422: @59 = dense(@1) */
  casadi_densify(w1, casadi_s13, w59, 0);
  /* #423: @60 = mac(@50,@59,@60) */
  for (i=0, rr=w60; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w50+j, tt=w59+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #424: {@61, @36, @53, @52, @8, @37, @67, @22, @20, @21, @12} = vertsplit(@60) */
  w61 = w60[0];
  w36 = w60[1];
  w53 = w60[2];
  w52 = w60[3];
  w8 = w60[4];
  w37 = w60[5];
  w67 = w60[6];
  w22 = w60[7];
  w20 = w60[8];
  w21 = w60[9];
  w12 = w60[10];
  /* #425: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #426: @4 = (@4/@10) */
  w4 /= w10;
  /* #427: @64 = 0 */
  w64 = 0.;
  /* #428: @60 = @15; (@60[1] = @64) */
  casadi_copy(w15, 11, w60);
  for (rr=w60+1, ss=(&w64); rr!=w60+2; rr+=1) *rr = *ss++;
  /* #429: @64 = @60[0] */
  for (rr=(&w64), ss=w60+0; ss!=w60+1; ss+=1) *rr++ = *ss;
  /* #430: @4 = (@4*@64) */
  w4 *= w64;
  /* #431: @4 = (-@4) */
  w4 = (- w4 );
  /* #432: @11 = (@11/@10) */
  w11 /= w10;
  /* #433: @63 = @15[1] */
  for (rr=(&w63), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #434: @11 = (@11*@63) */
  w11 *= w63;
  /* #435: @4 = (@4-@11) */
  w4 -= w11;
  /* #436: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #437: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #438: @4 = (@4/@7) */
  w4 /= w7;
  /* #439: @3 = (@3*@4) */
  w3 *= w4;
  /* #440: @64 = (@64/@10) */
  w64 /= w10;
  /* #441: @6 = (@6*@64) */
  w6 *= w64;
  /* #442: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #443: @3 = (@3+@6) */
  w3 += w6;
  /* #444: @61 = (@61+@3) */
  w61 += w3;
  /* #445: (@55[0] = @61) */
  for (rr=w55+0, ss=(&w61); rr!=w55+1; rr+=1) *rr = *ss++;
  /* #446: @63 = (@63/@10) */
  w63 /= w10;
  /* #447: @13 = (@13*@63) */
  w13 *= w63;
  /* #448: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #449: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #450: @9 = (@9*@4) */
  w9 *= w4;
  /* #451: @13 = (@13+@9) */
  w13 += w9;
  /* #452: @36 = (@36+@13) */
  w36 += w13;
  /* #453: (@55[1] = @36) */
  for (rr=w55+1, ss=(&w36); rr!=w55+2; rr+=1) *rr = *ss++;
  /* #454: (@55[2] = @53) */
  for (rr=w55+2, ss=(&w53); rr!=w55+3; rr+=1) *rr = *ss++;
  /* #455: @41 = zeros(4x1) */
  casadi_clear(w41, 4);
  /* #456: @50 = zeros(11x11) */
  casadi_clear(w50, 121);
  /* #457: @54 = @54' */
  /* #458: @50 = mac(@59,@54,@50) */
  for (i=0, rr=w50; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w59+j, tt=w54+i*1; k<1; ++k) *rr += ss[k*11]**tt++;
  /* #459: @68 = @50' */
  for (i=0, rr=w68, cs=w50; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #460: {@29, @71, @45} = horzsplit(@68) */
  casadi_copy(w68, 33, w29);
  casadi_copy(w68+33, 44, w71);
  casadi_copy(w68+77, 44, w45);
  /* #461: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #462: {NULL, @18, NULL} = horzsplit(@30) */
  casadi_copy(w30+21, 9, w18);
  /* #463: @53 = dot(@19, @18) */
  w53 = casadi_dot(9, w19, w18);
  /* #464: @53 = (2.*@53) */
  w53 = (2.* w53 );
  /* #465: (@41[0] += @53) */
  for (rr=w41+0, ss=(&w53); rr!=w41+1; rr+=1) *rr += *ss++;
  /* #466: @69 = (@26*@18) */
  for (i=0, rr=w69, cs=w18; i<9; ++i) (*rr++)  = (w26*(*cs++));
  /* #467: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #468: @70 = @27' */
  for (i=0, rr=w70, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #469: @17 = mac(@70,@18,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w70+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #470: @69 = (@69+@17) */
  for (i=0, rr=w69, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #471: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #472: @70 = @19' */
  for (i=0, rr=w70, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #473: @17 = mac(@18,@70,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w70+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #474: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #475: @69 = (@69+@17) */
  for (i=0, rr=w69, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #476: @26 = @69[5] */
  for (rr=(&w26), ss=w69+5; ss!=w69+6; ss+=1) *rr++ = *ss;
  /* #477: (@41[1] += @26) */
  for (rr=w41+1, ss=(&w26); rr!=w41+2; rr+=1) *rr += *ss++;
  /* #478: @26 = 0 */
  w26 = 0.;
  /* #479: (@69[5] = @26) */
  for (rr=w69+5, ss=(&w26); rr!=w69+6; rr+=1) *rr = *ss++;
  /* #480: @26 = @69[2] */
  for (rr=(&w26), ss=w69+2; ss!=w69+3; ss+=1) *rr++ = *ss;
  /* #481: @26 = (-@26) */
  w26 = (- w26 );
  /* #482: (@41[2] += @26) */
  for (rr=w41+2, ss=(&w26); rr!=w41+3; rr+=1) *rr += *ss++;
  /* #483: @26 = 0 */
  w26 = 0.;
  /* #484: (@69[2] = @26) */
  for (rr=w69+2, ss=(&w26); rr!=w69+3; rr+=1) *rr = *ss++;
  /* #485: @26 = @69[1] */
  for (rr=(&w26), ss=w69+1; ss!=w69+2; ss+=1) *rr++ = *ss;
  /* #486: (@41[3] += @26) */
  for (rr=w41+3, ss=(&w26); rr!=w41+4; rr+=1) *rr += *ss++;
  /* #487: @26 = 0 */
  w26 = 0.;
  /* #488: (@69[1] = @26) */
  for (rr=w69+1, ss=(&w26); rr!=w69+2; rr+=1) *rr = *ss++;
  /* #489: @26 = @69[7] */
  for (rr=(&w26), ss=w69+7; ss!=w69+8; ss+=1) *rr++ = *ss;
  /* #490: @26 = (-@26) */
  w26 = (- w26 );
  /* #491: (@41[1] += @26) */
  for (rr=w41+1, ss=(&w26); rr!=w41+2; rr+=1) *rr += *ss++;
  /* #492: @26 = 0 */
  w26 = 0.;
  /* #493: (@69[7] = @26) */
  for (rr=w69+7, ss=(&w26); rr!=w69+8; rr+=1) *rr = *ss++;
  /* #494: @26 = @69[6] */
  for (rr=(&w26), ss=w69+6; ss!=w69+7; ss+=1) *rr++ = *ss;
  /* #495: (@41[2] += @26) */
  for (rr=w41+2, ss=(&w26); rr!=w41+3; rr+=1) *rr += *ss++;
  /* #496: @26 = 0 */
  w26 = 0.;
  /* #497: (@69[6] = @26) */
  for (rr=w69+6, ss=(&w26); rr!=w69+7; rr+=1) *rr = *ss++;
  /* #498: @26 = @69[3] */
  for (rr=(&w26), ss=w69+3; ss!=w69+4; ss+=1) *rr++ = *ss;
  /* #499: @26 = (-@26) */
  w26 = (- w26 );
  /* #500: (@41[3] += @26) */
  for (rr=w41+3, ss=(&w26); rr!=w41+4; rr+=1) *rr += *ss++;
  /* #501: @39 = (@41/@24) */
  for (i=0, rr=w39, cr=w41; i<4; ++i) (*rr++)  = ((*cr++)/w24);
  /* #502: @25 = (@25/@24) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) /= w24;
  /* #503: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) *rr++ = (- *cs++ );
  /* #504: @26 = dot(@25, @41) */
  w26 = casadi_dot(4, w25, w41);
  /* #505: @26 = (@26/@24) */
  w26 /= w24;
  /* #506: @23 = (@26*@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w26*(*cs++));
  /* #507: @39 = (@39+@23) */
  for (i=0, rr=w39, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #508: {@26, @24, @53, @36} = vertsplit(@39) */
  w26 = w39[0];
  w24 = w39[1];
  w53 = w39[2];
  w36 = w39[3];
  /* #509: @52 = (@52+@26) */
  w52 += w26;
  /* #510: (@55[3] = @52) */
  for (rr=w55+3, ss=(&w52); rr!=w55+4; rr+=1) *rr = *ss++;
  /* #511: @8 = (@8+@24) */
  w8 += w24;
  /* #512: (@55[4] = @8) */
  for (rr=w55+4, ss=(&w8); rr!=w55+5; rr+=1) *rr = *ss++;
  /* #513: @37 = (@37+@53) */
  w37 += w53;
  /* #514: (@55[5] = @37) */
  for (rr=w55+5, ss=(&w37); rr!=w55+6; rr+=1) *rr = *ss++;
  /* #515: @67 = (@67+@36) */
  w67 += w36;
  /* #516: (@55[6] = @67) */
  for (rr=w55+6, ss=(&w67); rr!=w55+7; rr+=1) *rr = *ss++;
  /* #517: (@55[7] = @22) */
  for (rr=w55+7, ss=(&w22); rr!=w55+8; rr+=1) *rr = *ss++;
  /* #518: (@55[8] = @20) */
  for (rr=w55+8, ss=(&w20); rr!=w55+9; rr+=1) *rr = *ss++;
  /* #519: (@55[9] = @21) */
  for (rr=w55+9, ss=(&w21); rr!=w55+10; rr+=1) *rr = *ss++;
  /* #520: @43 = zeros(4x4) */
  casadi_clear(w43, 16);
  /* #521: @47 = @42' */
  for (i=0, rr=w47, cs=w42; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #522: @44 = @45' */
  for (i=0, rr=w44, cs=w45; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #523: {NULL, @42} = horzsplit(@44) */
  casadi_copy(w44+28, 16, w42);
  /* #524: @42 = (-@42) */
  for (i=0, rr=w42, cs=w42; i<16; ++i) *rr++ = (- *cs++ );
  /* #525: @43 = mac(@47,@42,@43) */
  for (i=0, rr=w43; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w47+j, tt=w42+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #526: @21 = 0 */
  w21 = 0.;
  /* #527: (@43[15] = @21) */
  for (rr=w43+15, ss=(&w21); rr!=w43+16; rr+=1) *rr = *ss++;
  /* #528: @21 = 0 */
  w21 = 0.;
  /* #529: (@43[11] = @21) */
  for (rr=w43+11, ss=(&w21); rr!=w43+12; rr+=1) *rr = *ss++;
  /* #530: @21 = 0 */
  w21 = 0.;
  /* #531: (@43[7] = @21) */
  for (rr=w43+7, ss=(&w21); rr!=w43+8; rr+=1) *rr = *ss++;
  /* #532: @21 = 0 */
  w21 = 0.;
  /* #533: (@43[3] = @21) */
  for (rr=w43+3, ss=(&w21); rr!=w43+4; rr+=1) *rr = *ss++;
  /* #534: @21 = 0 */
  w21 = 0.;
  /* #535: (@43[14] = @21) */
  for (rr=w43+14, ss=(&w21); rr!=w43+15; rr+=1) *rr = *ss++;
  /* #536: @21 = 0 */
  w21 = 0.;
  /* #537: (@43[10] = @21) */
  for (rr=w43+10, ss=(&w21); rr!=w43+11; rr+=1) *rr = *ss++;
  /* #538: @21 = 0 */
  w21 = 0.;
  /* #539: (@43[6] = @21) */
  for (rr=w43+6, ss=(&w21); rr!=w43+7; rr+=1) *rr = *ss++;
  /* #540: @21 = 0 */
  w21 = 0.;
  /* #541: (@43[2] = @21) */
  for (rr=w43+2, ss=(&w21); rr!=w43+3; rr+=1) *rr = *ss++;
  /* #542: @21 = 0 */
  w21 = 0.;
  /* #543: (@43[13] = @21) */
  for (rr=w43+13, ss=(&w21); rr!=w43+14; rr+=1) *rr = *ss++;
  /* #544: @21 = 0 */
  w21 = 0.;
  /* #545: (@43[9] = @21) */
  for (rr=w43+9, ss=(&w21); rr!=w43+10; rr+=1) *rr = *ss++;
  /* #546: @21 = 0 */
  w21 = 0.;
  /* #547: (@43[5] = @21) */
  for (rr=w43+5, ss=(&w21); rr!=w43+6; rr+=1) *rr = *ss++;
  /* #548: @21 = @43[1] */
  for (rr=(&w21), ss=w43+1; ss!=w43+2; ss+=1) *rr++ = *ss;
  /* #549: @34 = (@34*@21) */
  w34 *= w21;
  /* #550: @12 = (@12+@34) */
  w12 += w34;
  /* #551: @34 = 0 */
  w34 = 0.;
  /* #552: (@43[1] = @34) */
  for (rr=w43+1, ss=(&w34); rr!=w43+2; rr+=1) *rr = *ss++;
  /* #553: @34 = 0 */
  w34 = 0.;
  /* #554: (@43[12] = @34) */
  for (rr=w43+12, ss=(&w34); rr!=w43+13; rr+=1) *rr = *ss++;
  /* #555: @34 = 0 */
  w34 = 0.;
  /* #556: (@43[8] = @34) */
  for (rr=w43+8, ss=(&w34); rr!=w43+9; rr+=1) *rr = *ss++;
  /* #557: @34 = @43[4] */
  for (rr=(&w34), ss=w43+4; ss!=w43+5; ss+=1) *rr++ = *ss;
  /* #558: @33 = (@33*@34) */
  w33 *= w34;
  /* #559: @12 = (@12+@33) */
  w12 += w33;
  /* #560: @44 = @71' */
  for (i=0, rr=w44, cs=w71; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #561: {NULL, @43, NULL} = horzsplit(@44) */
  casadi_copy(w44+12, 16, w43);
  /* #562: @43 = (@32*@43) */
  for (i=0, rr=w43, cs=w43; i<16; ++i) (*rr++)  = (w32*(*cs++));
  /* #563: @47 = @43' */
  for (i=0, rr=w47, cs=w43; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #564: {@39, @23, @25, @41} = horzsplit(@47) */
  casadi_copy(w47, 4, w39);
  casadi_copy(w47+4, 4, w23);
  casadi_copy(w47+8, 4, w25);
  casadi_copy(w47+12, 4, w41);
  /* #565: @41 = @41' */
  /* #566: {@32, NULL, NULL, NULL} = horzsplit(@41) */
  w32 = w41[0];
  /* #567: @12 = (@12+@32) */
  w12 += w32;
  /* #568: @25 = @25' */
  /* #569: {NULL, @32, NULL, NULL} = horzsplit(@25) */
  w32 = w25[1];
  /* #570: @12 = (@12-@32) */
  w12 -= w32;
  /* #571: @23 = @23' */
  /* #572: {NULL, NULL, @32, NULL} = horzsplit(@23) */
  w32 = w23[2];
  /* #573: @12 = (@12+@32) */
  w12 += w32;
  /* #574: @39 = @39' */
  /* #575: {NULL, NULL, NULL, @32} = horzsplit(@39) */
  w32 = w39[3];
  /* #576: @12 = (@12-@32) */
  w12 -= w32;
  /* #577: (@55[10] = @12) */
  for (rr=w55+10, ss=(&w12); rr!=w55+11; rr+=1) *rr = *ss++;
  /* #578: @55 = @55' */
  /* #579: @40 = mac(@55,@49,@40) */
  for (i=0, rr=w40; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w55+j, tt=w49+i*11; k<11; ++k) *rr += ss[k*1]**tt++;
  /* #580: @62 = mac(@40,@38,@62) */
  for (i=0, rr=(&w62); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w40+j, tt=w38+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #581: @2 = (@2+@62) */
  w2 += w62;
  /* #582: @62 = 0 */
  w62 = 0.;
  /* #583: @1 = all_10(1x2) */
  casadi_fill(w1, 2, 10.);
  /* #584: @14 = vertcat(@35, @0) */
  rr=w14;
  *rr++ = w35;
  *rr++ = w0;
  /* #585: @62 = mac(@1,@14,@62) */
  for (i=0, rr=(&w62); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w14+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #586: @2 = (@2+@62) */
  w2 += w62;
  /* #587: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_constr_h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    case 3: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 927;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
